### ISSUE TITLE
OpenBLAS is not using provided LAPACK sources

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild-easyconfigs#1050]
The OpenBLAS 0.2.8 and 0.2.9 easyconfigs we're using now are not using the provided LAPACK sources, but are resorting to the `lapack-netlib` included in the OpenBLAS sources.

For OpenBLAS 0.2.9 and more recent this is not a big problem, since the LAPACK included in the sources matching the one we're passing it (3.5.0), see https://github.com/xianyi/OpenBLAS/blob/develop/lapack-netlib/README .

**Comment by akesandgren** [comment]
Still is still a problem for newer openblas/lapack combos, like openblas-0.2.18-lapack-3.6.1 where openblas contains lapack-3.6.0
I have a fix for this and will send a PR soon

**Comment by akesandgren** [comment]
PR 3700 added

**Comment by akesandgren** [comment]
Unfortunately the patch in PR 3700 is not good enough to make me add patches onto LAPACK after it has been unpacked, which is needed to fix some compile time bugs...

**Comment by akesandgren** [comment]
I'll withdraw that PR. I really need to get this done the correct way to solve all build problems.

**Comment by boegel** [comment]
@akesandgren thanks for looking into this!

**Comment by akesandgren** [comment]
Made a new PR (3701) that handles this in a much better way, and doesn't include patches.

It also makes it possible to add patches on to of the unpacked lapack to deal with compiler problems (and lapack bugs).

I'll start generating more PR for those problems, if this one gets accepted.

**Comment by boegel** [comment]
fixed by #3701 & #3795
