### ISSUE TITLE
sanity checks fails on Python package because of capitalization 

### ISSUE THREAD

**Issue by GiannisA** [hpcugent/easybuild-easyconfigs#1205]
Hello,

I am having some issues with easybuild while trying to build the Python Imaging Library (PIL) using a config file of my own.
More specifically, sanity check fails as it tries to run 'python -c "import pil"', while the name of the module is PIL. I have added a corrected sanity check command in my easybuild file, that passes the test (as seen in the log), but it keeps breaking on the default test. Going through the log file, I got some hints (not really sure) that you use the name of the module in lower case in the tests, which as it seems is not always the case.
Maybe I wasn't thorough enough, but I couldn't find any way to bypass the default sanity check without having to modify the pythonpackage block or create a new one.
Thank you for you time
Giannis

config file and error message:

PIL-1.1.7-goolf-1.4.10-Python-2.7.3:
easyblock = "PythonPackage"

name = 'PIL'
version = '1.1.7'

homepage = 'http://www.pythonware.com/products/pil/'
description = " Python Imaging Library (PIL) adds image processing capabilities to your Python interpreter"
toolchain = {'name': 'goolf', 'version': '1.4.10'}

sources = ['Imaging-%(version)s.tar.gz']
source_urls = ['http://effbot.org/media/downloads/']

python = 'Python'
pythonver = '2.7.3'
pythonshortversion = '2.7'

versionsuffix = '-%s-%s' % (python, pythonver)

dependencies = [(python, pythonver),('zlib', '1.2.7'),('lxml', '3.1.2', versionsuffix),('freetype', '2.4.11')]

sanity_check_commands = [('python', '-c "import PIL"')]

moduleclass = 'tools'

error msg:
== sanity checking...
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/PIL/1.1.7/goolf-1.4.10-Python-2.7.3): build failed (first 300 chars): EasyBuild crashed with an error (at easybuild/framework/easyblock.py:1578 in sanity_check_step): Sanity check failed: PIL failed to install, cmd 'python -c "import pil"' (stdin: None) output: Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named pil

== Results of the build can be found in the log file /tmp/easybuild-nc4ZWw/easybuild-PIL-1.1.7-20141121.173411.kmlkD.log
ERROR: EasyBuild crashed with an error (at easybuild/main.py:112 in build_and_install_software): Build of /gpfs/h/gashiotis/foo/configs/p/PIL/PIL-1.1.7-goolf-1.4.10-Python-2.7.3.eb failed (err: 'build failed (first 300 chars): EasyBuild crashed with an error (at easybuild/framework/easyblock.py:1578 in sanity_check_step): Sanity check failed: PIL failed to install, cmd \'python -c "import pil"\' (stdin: None) output: Traceback (most recent call last):\n  File "<string>", line 1, in <module>\nImportError: No module named pil\n')

**Comment by npklein** [comment]
In case someone else ends up here after searching this problem, remove ```sanity_check_commands = [('python', '-c "import PIL"')]``` and instead add ```options = {'modulename': 'PIL'}``` (from Jack Perdue on e-mail list)

**Comment by boegel** [comment]
Oh waw, this one clearly went under the radar somehow...

Sorry for never answering this @GiannisA. :(

**Comment by boegel** [comment]
And thanks @npklein for mentioning the correct thing to do in case someone bumps into this!

**Comment by deniskristak** [comment]
@boegel happened to me as well..should i look into pythonpackage easyblock and try to fix it? seems that PythonBundle has this fixed

**Comment by boegel** [comment]
@deniskristak I don't think there's anything to fix here?

`PythonPackage` will be default to an import with the package name but lowercase and replacing `-` with `_`.
For Python packages that don't match this pattern (like `Pillow` where you need to use `import PIL`), you can specify the correct name via `modulename` as discussed above.
