### ISSUE TITLE
Python sqlite3 dependency

### ISSUE THREAD

**Issue by gjbex** [hpcugent/easybuild-easyconfigs#1304]
The current Python 2.x easyconfigs don't contain a dependency on SQLite3.  This implies that the sqlite module in the standard library is non functional, which is somewhat bizarre.

I'd suggest to add this dependency.

**Comment by wpoely86** [comment]
Good point. @boegel lets fix this in #1291 ?

**Comment by boegel** [comment]
I was unaware of this.

I'd prefer opening a separate PR for this, since #1291 is ready to go now.
 
I suggest we only do this for recent Python versions, maybe even only v2.7.9? I see no reason to backport this 'fix' to older Python easyconfigs, especially since the latest SQLite3 version may not be working with older Python versions, etc.

@gjbex: up for fixing this with a PR?

**Comment by gjbex** [comment]
Sure, no problem.  I've fixed this for 2014a at some point, but I forgot
about it until after I did the PR.

On Thu, Jan 15, 2015 at 10:12 PM, Kenneth Hoste <notifications@github.com>
wrote:

> I was unaware of this.
>
> I'd prefer opening a separate PR for this, since #1291
> <https://github.com/hpcugent/easybuild-easyconfigs/pull/1291> is ready to
> go now.
>
> I suggest we only do this for recent Python versions, maybe even only
> v2.7.9? I see no reason to backport this 'fix' to older Python easyconfigs,
> especially since the latest SQLite3 version may not be working with older
> Python versions, etc.
>
> @gjbex <https://github.com/gjbex>: up for fixing this with a PR?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hpcugent/easybuild-easyconfigs/issues/1304#issuecomment-70162503>
> .
>



-- 
- dr. Geert Jan BEX
- HPC analyst/consultant Hasselt University & University of Leuven
- email:                geertjan.bex@uhasselt.be
- homepage:         http://alpha.uhasselt.be/~gjb/
- PGP public key: http://alpha.uhasselt.be/~gjb/pgp.txt
---------------------------------------------------------

**Comment by JensTimmerman** [comment]
any updates on this?

**Comment by boegel** [comment]
@JensTimmerman: seems like a fixed easyconfig for Python v2.7.9 is available at https://github.com/hpcleuven/easybuild-easyconfigs/blob/feature/python_sqlite/easybuild/easyconfigs/p/Python/Python-2.7.9-intel-2015a.eb

**Comment by boegel** [comment]
fixed for Python v2.7.9 easyconfigs via #1468
