### ISSUE TITLE
R defaults to user home directory extensions location

### ISSUE THREAD

**Issue by rjeschmi** [hpcugent/easybuild-easyconfigs#1326]
When I run the easybuild install for R it defaults to my home directory.

It seems for users who may have previously installed local packages this is the default behaviour

```
> .libPaths()
[1] "/home/gareth/R/x86_64-unknown-linux-gnu-library/3.1"
[2] "/scratch/rob/eb-dev-root/easybuild/software/R/3.1.2-foss-2014b/lib64/R/library"
```

https://gist.github.com/rjeschmi/142922a66dfee995e7d7

**Comment by rjeschmi** [comment]
I think the calls to self.make_cmdline_cmd() here without prefix might be the culprit

https://github.com/hpcugent/easybuild-easyblocks/blob/0dfed6cbeeeef56c4c21bc5397623cd91b606ff4/easybuild/easyblocks/generic/rpackage.py#L183

**Comment by boegel** [comment]
That makes sense, but we need the alternative for `make_r_cmd` too, I think... Although that's used a lot less (only for versionless pkg specs, which are rare afaik).

We are setting the `prefix` when the R package is being installed as a stand-alone module (see `install_step`), so we need to figure out what to specify as a `prefix`... It'll be `os.path.join(self.installdir, <some>, <thing>)`.

**Comment by boegel** [comment]
probably fix available in https://github.com/hpcugent/easybuild-easyblocks/pull/551

**Comment by rjeschmi** [comment]
fixed in PR listed above
