### ISSUE TITLE
Undifined reference to symbol while building Cufflinks on Debian Wheezy

### ISSUE THREAD

**Issue by sylmarien** [hpcugent/easybuild-easyconfigs#1333]
Hello,

I'm encountering an issue when I try to build Cufflinks 2.0.2 (with either ictce-5.3.0 or goolf-1.4.10) on Debian Wheezy.

The error message is the same in both cases: 
`/usr/bin/ld: gtf_to_sam.o: undefined reference to symbol '_ZN5boost6system15system_categoryEv'`

Here is the full log:
https://gist.github.com/7a90c77572959d5f7496.git

Thanks for the help, ask me if you want more info on the matter.

**Comment by boegel** [comment]
@wpoely86 or @fgeorgatos: any idea on this, since you're familiar with Debian (@wpoely86 is with C++)?

**Comment by wpoely86** [comment]
There cause of the error is easy. It's missing a linkage to `libboost_system`. Adding `-lboost_system` will fix it. The question is why does this not happen automatically. Does it work on RHEL?

**Comment by wpoely86** [comment]
@sylmarien could you also post the `config.log`?

**Comment by sylmarien** [comment]
@wpoely86 Here is the associated config.log:
https://gist.github.com/sylmarien/e47ab66060d6a4b93842

I didn't check on RHEL, I don't have an environment to test it on it right now.

**Comment by boegel** [comment]
@sylmarien: can you share the easyconfig you're using? We can give it a try on RHEL.

**Comment by boegel** [comment]
@sylmarien: nevermind, you're probably using the existing easyconfig that's available in EasyBuild?

**Comment by sylmarien** [comment]
@boegel Yes I use the ones available in EasyBuild.

**Comment by boegel** [comment]
OK, in that case: @wpoely86: yes, this works on RHEL-like systems.

**Comment by wpoely86** [comment]
@boegel you wouldn't happen to have a build log of it?

**Comment by boegel** [comment]
@wpoely86: full debug log at https://gist.github.com/boegel/39d8632e71a85afa0fe7

**Comment by wpoely86** [comment]
Okay, there a 3 ways out of this:
- Just use `2.1.0` where it is fixed
- Backport the fix in `2.0.2`. It comes down to adding some lines to `configure.ac`
- The dirty trick: do `preconfigopts=' LDFLAGS="-lboost_system" '` This should cause no harm as a modern linker will not link to a library if it does not need any of it's symbols.

**Comment by boegel** [comment]
@wpoely86: let's open a PR for option 3 in the 2.0.2 Cufflinks easyconfigs? I don't think it's that dirty?

**Comment by boegel** [comment]
@wpoely86: should be `LDFLAGS="$LDFLAGS -lboost_system"` btw, `eb` also sets `$LDFLAGS`

**Comment by wpoely86** [comment]
@sylmarien can you give #1335 a spin?

**Comment by sylmarien** [comment]
@wpoely86 I'm on it, it's currently building, we'll see if it works soon.

**Comment by sylmarien** [comment]
@wpoely86 @boegel Ok, the fix works fine. It builds without problem. (only tried the goolf version, if there is any problem wit the ictce version I'll let you know)

Thanks for the help!

**Comment by boegel** [comment]
let's follow up in #1335, but that seems like a proper fix indeed

thanks @wpoely86!
