### ISSUE TITLE
Perl build fails at sanity check step on Debian Wheezy

### ISSUE THREAD

**Issue by sylmarien** [hpcugent/easybuild-easyconfigs#1373]
Hello,

I've been trying to build Perl 5.16.3 on Debian Wheezy. While the bare version builds without any problem (for both ictce-5.3.0 and goolf-1.4.10), the one with the modules fails at the sanity check step (for both toolchains too). I'm using the easyconfig files available in EasyBuild.  
The problem seems to come from the modules, but I don't really know how to solve this problem. I checked the source links and none of the link is currently dead, so the problem isn't there.

Here is the full log:  
https://gist.github.com/sylmarien/73cd7b5f346e37038fd7

Thank you for you help, I'll be around if you need any more detail.

**Comment by boegel** [comment]
@sylmarien: thanks for reporting this

Here's what I see popping up in the logs when EasyBuild is performing the sanity check for the extensions:

```
== 2015-02-04 15:34:31,925 main.EB_Perl WARNING Extension: Tree::DAG_Node failed to install, cmd 
'perldoc -lm Tree::DAG_Node ' (stdin: None)
output: /bin/bash: /mnt/gaiagpfs/users/workdirs/mschmitt-easybuild/.local/resif/devel/v0.0-20150122/issue_Perl/software/lang/Perl/5.16.3-goolf-1.4.10/bin/perldoc:
/mnt/gaiagpfs/users/workdirs/mschmitt-easybuild/.local/resif/devel/v0.0-201501: bad interpreter: No such file or directory

== 2015-02-04 15:34:31,926 main.EB_Perl WARNING Sanity check for Tree::DAG_Node failed: Tree::DAG_Node failed to install, cmd
'perldoc -lm Tree::DAG_Node ' (stdin: None)
output: /bin/bash: /mnt/gaiagpfs/users/workdirs/mschmitt-easybuild/.local/resif/devel/v0.0-20150122/issue_Perl/software/lang/Perl/5.16.3-goolf-1.4.10/bin/perldoc:
 /mnt/gaiagpfs/users/workdirs/mschmitt-easybuild/.local/resif/devel/v0.0-201501: bad interpreter: No such file or directory
```

I've seen similar issues like this; it seems like the install location of `perl` (or another binary Perl provides) is injected into the shebang header line of `perldoc`, but because the installation path is too long, it gets truncated, causing perldoc to be broken.

Can you show us the first couple of lines of the `perldoc` script at `/mnt/gaiagpfs/users/workdirs/mschmitt-easybuild/.local/resif/devel/v0.0-20150122/issue_Perl/software/lang/Perl/5.16.3-goolf-1.4.10/bin/perldoc`?

**Comment by sylmarien** [comment]
@boegel Thanks for your answer, here are the first lines of perldoc:  
```
#!/mnt/gaiagpfs/users/workdirs/mschmitt-easybuild/.local/resif/devel/v0.0-20150122/issue_Perl/software/lang/Perl/5.16.3-goolf-1.4.10/bin/perl
    eval 'exec /mnt/gaiagpfs/users/workdirs/mschmitt-easybuild/.local/resif/devel/v0.0-20150122/issue_Perl/software/lang/Perl/5.16.3-goolf-1.4.10/bin/perl -S $0 ${1+"$@"}'
        if 0;
```

**Comment by boegel** [comment]
That confirms my suspicion... Although the full line is there, it's getting truncated, only the first N characters of the `#!` line are actually used, the others are simply dropped, which explains the error messages above.

A proper way of fixing this would be to make sure that Perl doesn't use this resolved path, but rather just uses `#!/usr/bin/env perl` instead. I'm not sure how difficult that would be...

**Comment by sylmarien** [comment]
@boegel Indeed I checked and the current limit on the system for the length of the shebang line is at 127 characters. (And it doesn't look like it is conceivable to increase this limit since it seems to require to recompile the kernel)

I don't know either how I would do that, but is it even the right thing to do ? That would make the module use the perl from the system instead of the module itself. Isn't that something we usually want to avoid?

I don't think much can be done apart from starting closer from the root which is what I'm going to do when I will build on a production level (I will be well below the 127 characters limit).

I don't think anything more can be done at this point. Except if you have anything to add on the matter, I think I can close this issue.
