### ISSUE TITLE
Distribution-related dependencies in some easyconfigs

### ISSUE THREAD

**Issue by sylmarien** [hpcugent/easybuild-easyconfigs#1374]
Hello,

I just wanted to point out that some easyconfig files contain system dependencies which names differ depending on the distribution used.

As an example in XCrySDen-1.5.53-goolf-1.4.10.eb, there is a dependency on the libXmu-devel package which is the name of the package on the RHEL-like distributions. Its Debian equivalent for example is libXmu-dev.

I also encountered this problem with Mesa (which is a dependency for XCrySDen) for a bit more packages. In order to help any other people that may encounter the same problem, here is a quick list of the Debian packages equivalents for this specific case:  
RHEL-like      ->    Debian equivalent  
libX11-devel  ->    libX11-dev  
xorg-x11-proto-devel -> x11proto-core-dev  
libXdamage-devel -> libXdamage-dev  
libXext-devel -> libXext-dev  
libXfixes-devel -> libXfixes-dev

Now, I don't know what could be done about that, I'm not sure that having "distribution-specific" easyconfig files would do any good, but it currently is "distribution-specific" already. A solution could be to have different options depending on the distribution (and then the checking at the beginning would use the correct one), but it could make the easyconfig files to just grow bigger and more complicated.

**Comment by boegel** [comment]
As mentioned in https://github.com/hpcugent/easybuild-easyconfigs/pull/1377#issuecomment-72909848, we have a way of dealing with this, i.e. using a tuple of options in `osdependencies`, e.g.:

```python
osdependencies = [('libX11-devel', 'libX11-dev')]
```

If one of both packages can be found, EasyBuild will be happy. If need be, you can skip this check using `--ignore-osdeps` if you know the package is actually available, but under a different name.

Even better: if you can, replace these kind of OS deps with proper dependencies installed via EasyBuild.

If this is an adequate answer to your questions, please close this issue.

**Comment by sylmarien** [comment]
@boegel Thank you for the answer, it indeed answers my question.
