### ISSUE TITLE
Python Tk dependency

### ISSUE THREAD

**Issue by a-mazur** [hpcugent/easybuild-easyconfigs#1402]
Current Python easyconfigs do not have a dependency on Tk. Therefore, Tkinter (Python2) and tkinter (Python3) modules are not functional, if system Tk libraries are not present

**Comment by boegel** [comment]
fixed in #1654 (non-Cray Python 2.7.9 easyconfigs), sanity check enhanced for Cray Python 2.7.9 easyconfigs in #1655 

easyconfig(s) for Python 2.7.10 include Tk dependency (see #1638, #1639)

Thanks for reporting this @a-mazur!
