### ISSUE TITLE
blast easyconfigs should be renamed

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-easyconfigs#1442]
Hi,

I realized that the blast easyconfigs should be renamed. Every blast version > 2.2.26 is named BLAST+ while versions <= 2.2.26 are named just BLAST

ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/LATEST/

ftp://ftp.ncbi.nlm.nih.gov/blast/executables/release/LATEST/

I found this problem because I am trying to write a easyconfig for a tool which have both BLAST and BLAST+ as dependency and with the current naming schema I cannot add both dependencies

**Comment by pescobar** [comment]
I have sent this PR which should fix it 

https://github.com/hpcugent/easybuild-easyconfigs/pull/1443

**Comment by fgeorgatos** [comment]
Hi Pablo,

I am possibly the perpetrator of the original naming and I confess of
pondering on which naming scheme would be good, back then.
At those times I felt that the "+" in the name may create all shorts of
troubles in other people's systems, so I played conservative.

However, I stand by your argumentation and think that now (ie. eb/v2.1) is
a good moment to introduce such a "fix".
Watch out for fancy build behavior over parallel filesystems. Fingers
crossed :-P

F.


On 4 March 2015 at 12:43, Pablo Escobar Lopez <notifications@github.com>
wrote:

> I have sent this PR which should fix it
>
> #1443 <https://github.com/hpcugent/easybuild-easyconfigs/pull/1443>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/hpcugent/easybuild-easyconfigs/issues/1442#issuecomment-77151093>
> .
>



-- 


echo "sysadmin know better bash than english"|sed s/min/mins/ \
  | sed 's/better bash/bash better/' # signal detected in a CERN forum

**Comment by boegel** [comment]
@pescobar: what tool is this? And do BLAST and BLAST+ provide different functionalities (that don't clash)?

**Comment by pescobar** [comment]
@boegel BLAST is a widely used tool in bioinformatics for sequence alignment

Both applications are from the same developers and I think they do the same but when they switched from BLAST to BLAST+ they did a big change, as example, the binary names in BLAST and BLAST+ are different. So even if both applications do the same they are not compatible so we could say they are different apps

**Comment by boegel** [comment]
OK, makes sense to rename them then. Let's follow-up on this in #1443.
