### ISSUE TITLE
tinker

### ISSUE THREAD

**Issue by fanourg** [hpcugent/easybuild-easyconfigs#153]
Have you already provides support for MD package "tinker"? If not I am interested of working on it.

**Comment by JensTimmerman** [comment]
see https://github.com/hpcugent/easybuild-easyconfigs/pull/1465

**Comment by boegel** [comment]
easyconfig in #153, easyblock required is contributed in https://github.com/hpcugent/easybuild-easyblocks/pull/578

**Comment by boegel** [comment]
support for building and installing TINKER has been merged, and will be included in the upcoming EasyBuild v2.1 (ETA: (end of) April'15)
