### ISSUE TITLE
Lose -gpfs from HDF5-1.8.14-intel-2015a-gpfs.eb 

### ISSUE THREAD

**Issue by JackPerdue** [hpcugent/easybuild-easyconfigs#1577]
AFAICT, the --with-gpfs option was last supported in 1.8.12.  After that (I believe) all functions utilizing GPFS hints were deprecated.  So we probably don't need this one (given possible confusion) distributed.

**Comment by pforai** [comment]
@JackPerdue any links to official docs on this one?

**Comment by boegel** [comment]
From the configure output in the HDF5 1.8.14 log:

```
configure: WARNING: unrecognized options: --enable-gpfs 
```

So, makes sense to drop the config option (and versionsuffix).

**Comment by boegel** [comment]
fix in #1657
