### ISSUE TITLE
OpenFOAM patches introduce environment variables into wmake build system

### ISSUE THREAD

**Issue by FokkeDijkstra** [hpcugent/easybuild-easyconfigs#1842]
I've installed OpenFOAM 2.3.1 using easybuild. I got questions from our users because they were not able to build their own OpenFOAM code using the OpenFOAM wmake build system.

I found out that in the wmake rules the environment variables $(MPICC) $(MPICXX) $(CFLAGS) and $(CXXFLAGS) were introduced. Since these are not set by the goolfc toolchain the build system breaks. And even if MPICC and MPICXX are set unoptimised code will be produced.

These changes in the wmake build system are introduced by the patch file cleanup-OpenFOAM-2.3.1.patch.
I am now fixing this by removing the settings for the compiler flags and introducing mpicc and mpic++ as compiler settings.

Can someone explain me the reason for these specific patches?

**Comment by boegel** [comment]
This patch is there to make ``wmake`` honor the build environment (`$MPICC`, `$CFLAGS`, etc.) as it is defined by EasyBuild when building/installing OpenFOAM.

But you're right, we've also had issues with people running into weird problems when trying to compile their own solvers. I just didn't realise it was our patch that was the cause of this problem...

Rather than removing those flags altogether, they should be modified such that the original value stays in place if they're not set. I.e., rather than doing this:

```diff
-cc          = icc
-cOPT        = -O3 -no-prec-div
+cc          = $(MPICC)
+cOPT        = $(CFLAGS)
```

we should be doing this instead (needs to be tested):

```diff
-cc          = icc
-cOPT        = -O3 -no-prec-div
+cc          = ${MPICC:=icc}
+cOPT        = ${CFLAGS:=-O3 -no-prec-div}
```
Can you see whether changing the patch to do this resolves the problem?

**Comment by FokkeDijkstra** [comment]
Unfortunately this does not work. The lines involved are parsed by make and not by the shell.
It should be possible to check in make if a variable is undefined, and set it if it is. I will check this route.

**Comment by FokkeDijkstra** [comment]
I found a way to set variables  in make if they are not defined. Unfortunately this only works for GNU make. The diffs  now look like this:

```diff
-cc          = gcc -m64
+MPICC       ?= gcc -m64
+cc          = $(MPICC)
```
and
```diff
-cOPT        = -O3
+CFLAGS      ?= -O3
+cOPT        = $(CFLAGS)
```

I was able to build and run OpenFOAM, using these patches. I also could compile plugins. I will now check with the user involved to see if he still finds issues.

**Comment by FokkeDijkstra** [comment]
Our cluster user reported that he now could run OpenFOAM, including compiling his own code. This has been done using a goolfc version of OpenFOAM.

For icc similar modifications should be made.

**Comment by boegel** [comment]
@FokkeDijkstra thanks for the feedback!

I'll try and get this fixed across the board

**Comment by boegel** [comment]
I'm working on PR https://github.com/hpcugent/easybuild-easyconfigs/pull/1920 that will fix this, let's follow up there.

Thanks for reporting this @FokkeDijkstra and figuring out a fix!

**Comment by boegel** [comment]
better workaround for this is implemented via the OpenFOAM easyblock, see https://github.com/hpcugent/easybuild-easyblocks/pull/688

**Comment by boegel** [comment]
fixed with https://github.com/hpcugent/easybuild-easyblocks/pull/688, just merged in, thanks again for reporting this @FokkeDijkstra and helping out with figuring out the fix!
