### ISSUE TITLE
Bioconductor bundle version updates

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-easyconfigs#1851]
Several components in the Bioconductor bundle require updates:

BioStrings 2.36.1 -> 2.36.3

**Comment by verdurin** [comment]
Biocparallel 1.2.9 -> 1.2.20

**Comment by verdurin** [comment]
BiocInstaller 1.18.3 -> 1.18.4

**Comment by verdurin** [comment]
limma 3.24.13 -> 3.24.15

**Comment by verdurin** [comment]
rtracklayer 1.28.6 -> 1.28.7

**Comment by verdurin** [comment]
NOISeq 2.12.0 .> 2.14.0

**Comment by verdurin** [comment]
BSgenome 1.36.2 -> 1.36.3

**Comment by verdurin** [comment]
VariantAnnotation 1.14.6 -> 1.14.10

**Comment by boegel** [comment]
see #1852, let's follow-up there
