### ISSUE TITLE
Update some easyconfigs for current dependencies

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-easyconfigs#1856]
For example, I need a version of GATK and Picardtools with the current version of Java 1.7.0 - minor release 80.

**Comment by boegel** [comment]
Done in #1857.

@verdurin: you don't need to create an issue for things you will be sending us a pull request for, it only creates duplicates in the issue tracker (every PR is also an issue), and more bookkeeping for us.

Just send us the PR. :-)
