### ISSUE TITLE
SAMtools : always built using gcc?

### ISSUE THREAD

**Issue by backelj** [hpcugent/easybuild-easyconfigs#1959]
Hello,

When I was looking at building TopHat-2.1.0-intel-2015b (using an adaption of an earlier EasyConfig file),  I noticed that samtools-0.1.18 is now included with TopHat (starting with version 2.0.13). But since it explicitly mentions CC=gcc and CFLAGS=... in it's Makefile, this samtools-0.1.18 was actually built with gcc instead as with icc.

This got me thinking to have a look at at EasyConfig files for SAMtools, for instance SAMtools-0.1.19-intel-2015a.eb. Here the patch SAMtools-0.1.19_Makefile-ncurses.patch is used, but it doesn't include anything for CC=icc and CFLAGS=..., so it is actually built with gcc.

So should we not add an extra patch which removes the CC and CCFLAGS lines at the beginning of the Makefile (or one that adds proper lines)?

-- Regards,

Franky

**Comment by fgeorgatos** [comment]
Hi @backelj,

in Makefiles, "hardwired" CC= definitions can be interestingly overriden from outside (try it).

This does not automatically make the process correct though, because someone has to do it; can you check what is the status, by dumping the environment with env or some other similar way?

Generally, I wonder how many bugs of this class we will be about to discover, once we start employing isolated builds in minimal environments where we actually will be *tracking* which compiler is called, which library is linked and what is missing. I'm sure, it's going to be entertaining!

**Comment by boegel** [comment]
I'd guess the SAMtools easyconfigs need something like this:

```python
buildopts = 'CC="$CC" CFLAGS="$CFLAGS"'
```

**Comment by boegel** [comment]
@backelj: let us know if you've tried the suggestion above; if it works as a fix, a pull request would be great :-)

**Comment by backelj** [comment]
Hi Kenneth,

Op 15-sep.-2015, om 17:08 heeft Kenneth Hoste <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

@backelj<https://github.com/backelj>: let us know if you've tried the suggestion above; if it works as a fix, a pull request would be great :-)

Yes, the buildopts does the trick!  I will check the available easyconfigs...

This makes me wonder: shouldn’t this be the default behavior?

— Franky

**Comment by boegel** [comment]
I consider this a bug in the makefile more than anything else.

Always doing this may lead to problems, for example if the Makefile does something like:

```
CC += --extra-flag-that-is-required-to-make-the-build-work
```

**Comment by backelj** [comment]
Op 16-sep.-2015, om 09:43 heeft Kenneth Hoste <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

I consider this a bug in the makefile more than anything else.

Always doing this may lead to problems, for example if the Makefile does something like:

CC += --extra-flag-that-is-required-to-make-the-build-work


Yes you are right.

— Franky

**Comment by boegel** [comment]
ping?

**Comment by boegel** [comment]
fixed with https://github.com/hpcugent/easybuild-easyblocks/pull/966

**Comment by boegel** [comment]
closing this, https://github.com/hpcugent/easybuild-easyblocks/pull/966 is merged
