### ISSUE TITLE
Meta-easyconfigs?

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-easyconfigs#2036]
I've had a request for the full SciPy Stack (http://www.scipy.org/stackspec.html). A lot of the components are already in EB, but it might be useful to be able to install them all as a single module, a bit like a meta-RPM.

Does this sound like something that would be useful/accepted?

**Comment by verdurin** [comment]
Okay, this is partially covered by #421. Anyway, I would be interested to hear whether this sort of more tailored meta-package would be welcomed.

**Comment by fgeorgatos** [comment]
+1. 
These meta packages reduce entropy across several clusters and basically they form the same role which an EB toolchain fulfills, at a higher level: provide a common substrate of a coherent software stack.

**Comment by boegel** [comment]
I guess the `Bundle` easyblock matches your need? See for example https://github.com/hpcugent/easybuild-easyconfigs/blob/master/easybuild/easyconfigs/h/HPCBIOS_LifeSciences/HPCBIOS_LifeSciences-20130829-ictce-5.3.0.eb .

It certainly makes sense to put them together under the `SymPy` flag

**Comment by verdurin** [comment]
Yes, I've been using `Bundle` and it works well.

I'll close this and any further discussion can happen in the specific PR.

Thanks.
