### ISSUE TITLE
build of GMP 6.0.0a fails because of missing M4 dependency

### ISSUE THREAD

**Issue by riccardomurri** [hpcugent/easybuild-easyconfigs#2095]
The `./configure` step of GMP 6.0.0a checks for the `m4` preprocessor
and stops if it's not found::

        checking for suitable m4... configure: error: No usable m4 in $PATH or /usr/5bin (see config.log for reasons).

However, the `GMP-6.0.0a-foss-2015a` easyconfig does not list M4 as a
dependency, and neither does any other GMP easyconfig on my system
(running EasyBuild 2.3.0).

**Comment by boegel** [comment]
That's a bug, it's not uncommon that dependencies that are typically available in the OS are not included in easyconfigs...

@riccardomurri: up for issuing a PR to fix this for the most recent GMP easyconfigs (i.e., 6.0.0 and more recent)?

Or maybe @wpoely86?

**Comment by riccardomurri** [comment]
@boegel done with PR #2096

**Comment by nathanhaigh** [comment]
I'm new to easybuild, so forgive my ignorance. On Ubuntu the package is `autotools-dev`. How does that get specified/dealt with in an easyconfig file?

**Comment by boegel** [comment]
@nathanhaigh: in EasyBuild, we typically don't make a distinction between devel and non-devel packages

You can include `Autotools` (which is a bundle with `Autoconf`, `Automake` and `libtool`, cfr. https://github.com/hpcugent/easybuild-easyconfigs/tree/master/easybuild/easyconfigs/a/Autotools) as a build dependency, see https://github.com/hpcugent/easybuild-easyconfigs/search?utf8=%E2%9C%93&q=autotools .

**Comment by nathanhaigh** [comment]
@boegel Got ya! Thanks for the clarification! :)

**Comment by boegel** [comment]
Let's follow-up in #2096, thanks for looking into this @riccardomurri!
