### ISSUE TITLE
icc can't compile std::vector with GCC 5.x headers

### ISSUE THREAD

**Issue by jas02** [hpcugent/easybuild-easyconfigs#2100]
Hi,

from Intel icc 2015.3 to current 2016.0.109 there is problem with GCC 5.x headers.

Please see https://software.intel.com/en-us/forums/intel-c-compiler/topic/565143

Problem won't be probably fixed so fast, because is present for some time now, without fix or workaround.

Please do not create new Intel toolchain 2016.00 with GCC 5.2.0 headers, but with 4.9.3 instead. 

Easyconfigs are in PR #1973 .

**Comment by wpoely86** [comment]
@jas02 thanks for letting us know. We will keep an eye on this.

**Comment by boegel** [comment]
seems like it's still a problem, even with icc 16.0.1...

"number one priority", they said...

**Comment by boegel** [comment]
It seems like this problem is fixed in the new 2016.2.181 release, cfr. https://software.intel.com/en-us/articles/intel-parallel-studio-xe-2016-composer-edition-compilers-fixes-list (look for DPD200365668).

So, do we use GCC 5.3.0 in `intel/2016.02` (cfr. #2523)?

**Comment by boegel** [comment]
Other potential issues with GCC 5.x are being uncovered (not related to Intel, but I figured I should mention it here too), cfr. https://github.com/openhpc/ohpc/issues/207#issuecomment-209976993

**Comment by boegel** [comment]
closing this, as we now have versions of the `intel` toolchain on top of GCC 5.3, cfr. #2523 and #3009
