### ISSUE TITLE
hwloc issues

### ISSUE THREAD

**Issue by nathanhaigh** [hpcugent/easybuild-easyconfigs#2224]
I'm trying really hard to get started with easybuild but I'm hitting issues with hwloc. It appears that something is amiss with the http://www.open-mpi.org/ website for versions older than 1.9 (what it now classes as "ancient").

The site seems to just hang for those downloads. This means that any tools that I try to install using easybuild, which has a dependency on hwloc < 1.9 won't install as the hwloc source can't be obtained. At the momment, this seems to affect a lot of easybuild tools.

So my questions are:
  * How to get around this?
  * Can I update the *.eb files so the tools I'm trying to install will depend on a more recent, accessible (>= 1.9) version of hwloc?

**Comment by nathanhaigh** [comment]
It appears things have fixed themselves and I can now access the hwloc files. However, I'd still like to get some pointers on the latter question.

**Comment by boegel** [comment]
The auto-download mechanism in EasyBuild is best effort, all kinds of things can go wrong upstream, as you've experienced.

You can download the `hwloc` tarball manually, and 'feed' it to EasyBuild in the source path (see http://easybuild.readthedocs.org/en/latest/Configuration.html#sourcepath) to dance around any auto-download issues.

You can also fiddle with the versions in the `.eb` files, sure, but then you may run into surprises later, e.g. version conflicts if you start installing things on top of your tweaked easyconfig (there can be only one software version in a (connected) dependency graph).
Creating/maintaining your own set of easyconfig files, where you freely choose versions, is something we encourage though, but it does move some of the burden to yourself.

If this answers your questions, please close this issue.

**Comment by nathanhaigh** [comment]
Thanks, I'll look into maintaining my own set of easyconfig files.
