### ISSUE TITLE
M4-1.4.17.eb needs to be a runtime dep of Bison-3.0.4.eb (not builddep) at least on RHEL5

### ISSUE THREAD

**Issue by JackPerdue** [hpcugent/easybuild-easyconfigs#2241]
Testing the new GCCcore on my systems.  So far so good on RHEL6, both x86 and Power7.  But RHEL5 x86 won't let me build binutils-2.25 using Bison with M4 as a builddep because the build of binutils at one points invokes "m4 --gnu <etc>" and the stock m4 on RHEL5.11 (currently using m4-1.4.5-3.el5.1.x86_64) doesn't support "--gnu".  

Changing M4 to a runtime dep for Bison fixes that.

**Comment by JackPerdue** [comment]
Note that on RHEL5, I also had to make the following change to M4-1.4.17-GCCcore-4.9.3.eb:
<pre>
18a19
> preconfigopts = 'CFLAGS="$CFLAGS -fgnu89-inline" && '
</pre>

else I get a lot of duplicate symbols from stdio.h (and others).  e.g. fgets

Has the new GCCcore been tested on RHEL5? (either via the EB test framework or by an individual)
I'm just curios if these problems are somehow related to our particular setup.

**Comment by JackPerdue** [comment]
Note I had the same problem as the first post with Bison-3.0.4-GCCcore-4.9.3.eb/M4-1.4.17-GCCcore-4.9.3.eb.   If M4 is only a builddep then when I try to build binutils-2.25-GCCcore-4.9.3.eb, it falls back to the system M4 which fails with the '--gnu' flag.

**Comment by JackPerdue** [comment]
FWIW (for future reference before I forget during the holiday), here's a diff of the changes I had to make for RHEL5.  Still not sure if this is a local problem or not.

[rhel5_6_2.50.diff.txt](https://github.com/hpcugent/easybuild-easyconfigs/files/70312/rhel5_6_2.50.diff.txt)

**Comment by boegel** [comment]
inline patch provided y @JackPerdue below

@JackPerdue: any updates on this?

```diff
--- /software/easybuild/ebfiles_repo_cleaned//ada/Bison/Bison-3.0.4.eb	2015-12-17 14:01:21.000000000 -0600
+++ /software/easybuild/ebfiles_repo_cleaned//eos/Bison/Bison-3.0.4.eb	2015-12-22 14:50:24.000000000 -0600
@@ -12,7 +12,7 @@
 sources = [SOURCELOWER_TAR_GZ]
 source_urls = [GNU_SOURCE]
 
-builddependencies = [('M4', '1.4.17')]
+dependencies = [('M4', '1.4.17')]
 
 sanity_check_paths = {
     'files': ["bin/%s" % x for x in ["bison", "yacc"]] + ["lib/liby.a"],
--- /software/easybuild/ebfiles_repo_cleaned//ada/Bison/Bison-3.0.4-GCC-4.9.3-binutils-2.25.eb	2015-11-16 23:20:43.000000000 -0600
+++ /software/easybuild/ebfiles_repo_cleaned//eos/Bison/Bison-3.0.4-GCC-4.9.3-binutils-2.25.eb	2015-12-22 14:41:25.000000000 -0600
@@ -13,11 +13,14 @@
 source_urls = [GNU_SOURCE]
 
 builddependencies = [
-    ('M4', '1.4.17'),
     # use same binutils version that was used when building GCC toolchain
     ('binutils', '2.25', '', True),
 ]
 
+dependencies = [
+    ('M4', '1.4.17'),
+]
+
 sanity_check_paths = {
     'files': ["bin/%s" % x for x in ["bison", "yacc"]] + ["lib/liby.a"],
     'dirs': [],
--- /software/easybuild/ebfiles_repo_cleaned//ada/Bison/Bison-3.0.4-GCCcore-4.9.3.eb	2015-12-17 14:01:21.000000000 -0600
+++ /software/easybuild/ebfiles_repo_cleaned//eos/Bison/Bison-3.0.4-GCCcore-4.9.3.eb	2015-12-22 14:41:24.000000000 -0600
@@ -13,11 +13,13 @@
 source_urls = [GNU_SOURCE]
 
 builddependencies = [
-    ('M4', '1.4.17'),
     # use same binutils version that was used when building GCCcore toolchain
     ('binutils', '2.25', '', True),
 ]
 
+dependencies = [
+    ('M4', '1.4.17'),
+]
 
 sanity_check_paths = {
     'files': ["bin/%s" % x for x in ["bison", "yacc"]] + ["lib/liby.a"],
--- /software/easybuild/ebfiles_repo_cleaned//ada/M4/M4-1.4.17-GCC-4.9.3-binutils-2.25.eb	2015-11-16 23:20:49.000000000 -0600
+++ /software/easybuild/ebfiles_repo_cleaned//eos/M4/M4-1.4.17-GCC-4.9.3-binutils-2.25.eb	2015-12-22 14:41:26.000000000 -0600
@@ -16,6 +16,7 @@
 # use same binutils version that was used when building GCC toolchain
 builddependencies = [('binutils', '2.25', '', True)]
 
+preconfigopts = 'CFLAGS="$CFLAGS -fgnu89-inline" && '
 configopts = "--enable-cxx"
 
 sanity_check_paths = {
--- /software/easybuild/ebfiles_repo_cleaned//ada/M4/M4-1.4.17-GCCcore-4.9.3.eb	2015-12-17 14:01:27.000000000 -0600
+++ /software/easybuild/ebfiles_repo_cleaned//eos/M4/M4-1.4.17-GCCcore-4.9.3.eb	2015-12-22 14:41:26.000000000 -0600
@@ -16,6 +16,7 @@
 # use same binutils version that was used when building GCC toolchain
 builddependencies = [('binutils', '2.25', '', True)]
 
+preconfigopts = 'CFLAGS="$CFLAGS -fgnu89-inline" && '
 configopts = "--enable-cxx"
 
 sanity_check_paths = {
--- /software/easybuild/ebfiles_repo_cleaned//ada/M4/M4-1.4.17-GNU-4.9.3-2.25.eb	2015-12-17 14:01:27.000000000 -0600
+++ /software/easybuild/ebfiles_repo_cleaned//eos/M4/M4-1.4.17-GNU-4.9.3-2.25.eb	2015-12-22 14:41:26.000000000 -0600
@@ -13,6 +13,7 @@
 sources = [SOURCELOWER_TAR_GZ]
 source_urls = [GNU_SOURCE]
 
+preconfigopts = 'CFLAGS="$CFLAGS -fgnu89-inline" && '
 configopts = "--enable-cxx"
 
 sanity_check_paths = {
--- /software/easybuild/ebfiles_repo_cleaned//ada/OpenMPI/OpenMPI-1.8.8-GNU-4.9.3-2.25.eb	2015-12-17 14:01:28.000000000 -0600
+++ /software/easybuild/ebfiles_repo_cleaned//eos/OpenMPI/OpenMPI-1.8.8-GNU-4.9.3-2.25.eb	2015-12-22 14:41:27.000000000 -0600
@@ -13,6 +13,7 @@
 
 dependencies = [('hwloc', '1.11.0')]
 
+preconfigopts = 'CFLAGS="$CFLAGS -fgnu89-inline" && '
 configopts = '--with-threads=posix --enable-shared --enable-mpi-thread-multiple --with-verbs '
 configopts += '--enable-mpirun-prefix-by-default '  # suppress failure modes in relation to mpirun path
 configopts += '--with-hwloc=$EBROOTHWLOC '  # hwloc support

```

**Comment by DirkdeDraak** [comment]
To confirm to @boegel , yes this is what I also found. M4 should be a dependency, rather than a builddependency.

**Comment by boegel** [comment]
Is requiring M4 next to Bison specific to binutils, or have you also seen this occur with other builds?

It looks like the binutils build procedure requires `m4`, rather than Bison calling `m4` at runtime?

If that's indeed the case, then the right solution is the add M4 as a build dep to binutils, rather than making M4 a runtime dep of Bison?

@JackPerdue: I don't think a lot of testing on RHEL5-like systems is still being done, we took those out of production a while ago at HPC-UGent.
Maybe it's better to open a separate issue for problems related to RHEL5?
We can add `-fgnu89-inline` to the M4 easyconfigs if it doesn't cause problems on other more recent systems.

**Comment by JackPerdue** [comment]
I guess its more a builddep of binutils than a rundep of Bison.  I'll have to see what happens if I make that change.

**Comment by boegel** [comment]
@JackPerdue: did you get a chance to play with this?

**Comment by JackPerdue** [comment]
@boegel: I managed to get this far
<pre>
[jack@login006 eos]$ ls -alR | grep 'Jan 21'
-rw-r--r-- 1 jack staff  1557 Jan 21 17:00 binutils-2.25.eb
-rw-r--r-- 1 jack staff   594 Jan 21 17:00 Bison-3.0.4.eb
-rw-r--r-- 1 jack staff   729 Jan 21 17:00 Bison-3.0.4-GCC-4.9.3-binutils-2.25.eb
-rw-r--r-- 1 jack staff  1473 Jan 21 17:00 GCC-4.9.3-binutils-2.25.eb
-rw-r--r-- 1 jack staff   859 Jan 21 17:00 M4-1.4.17-GCC-4.9.3-binutils-2.25.eb
</pre>
but everytime I sit down to go to the next step I get distracted. on what to build next to properly test.
I tried using --dep-graph but given RH5 which lacks a lot of python support (I have to load a python module to use EB which was stripped down for just basic EB) it doesn't work so I need to copy my ebfiles_repo to my Fedora box, install EB, set the ROBOTPATH to there and see if dep-graph will work there.  Is there a text version of dep-graph?  Perhaps that might put something out like the attached, imaginary/not-used/alternative approach (a doc I came up while pondering the whole GCC bootstrap thing).  RD=runtime-dep  BD=build-dep  TC=toolchain EB=easyblock

I'm working on it and I think I can clean this up a lot but I want to make sure I do it right and am struggling with the deps for now.   
[newgcc.txt](https://github.com/hpcugent/easybuild-easyconfigs/files/100150/newgcc.txt)

**Comment by JackPerdue** [comment]
In short... this probably needs to wait until after 2.6.0. I think you're right in what I changed but I haven't been able (had time) to rebuild to verify (new semester here started Tuesday). Same for any IBM XL .eb's I come up with based on this new approach to bootstrapping... probably won't make 2.6. If someone has problems on RHEL5 we can always point them here (or something).

**Comment by boegel** [comment]
@JackPerdue: build dependencies are now marked in the output of `--dep-graph` thanks to https://github.com/hpcugent/easybuild-framework/pull/1548; I guess we can extend on this to also mark the toolchain part, and maybe even to indicate which easyblock would be used
The closest thing to text output we support now is making `--dep-graph` spit out a `.dot` file, which is more-or-less human readable. You'll still need to have pygraph available though...

As far as I understand, fixing (part of) this issue is as simple as including `M4` as a build dep in the `binutils` easyconfigs. Or am I missing something here?

**Comment by JackPerdue** [comment]
Ken, no, I don't think you are missing anything.  I just want to rebuild from the start to make sure I'm not missing anything.  But there is a lot going on here (new boss with the new year and we will be moving offices next week far across campus, while trying to keep everything running and everyone happy... plus I've been distracted by trying to figure out a papiex[*] build for EB... and filing expense reports for the hackathon and SC15... and.... 

I should either just fire up an EC2 instance at AWS with RHEL5 for someone to play with or set up your logins on our systems now that you have the needed credentials.  But those take time too.

But I haven't forgotten about it.

**Comment by sguera** [comment]
I jump into this, since we had a similar issue while trying to install GCCCore on a new machine with Ubuntu 14.04. I already opened an issue here:
[https://github.com/hpcugent/easybuild-easyconfigs/issues/2384](url)

So far we are not able to go through it, at least not completely since there is always a new issue popping out with this installation.

**Comment by boegel** [comment]
@JackPerdue, @sguera: fixed with #2681 ?

**Comment by boegel** [comment]
I'm going to assume this is fixed with #2681, do let us know if that's not the case...

**Comment by sguera** [comment]
Hi @boegel ,

that fixed things for me..

**Comment by boegel** [comment]
@sguera thanks for reporting back!
