### ISSUE TITLE
samtools version documentation?

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-easyconfigs#2242]
I'd like to submit a PR for the new samtools 1.3 release, but I'm somewhat confused by all the different version of samtools easyconfigs that are currently available. Is there some documentation of their purpose somewhere?

**Comment by boegel** [comment]
@verdurin: I'm only seeing easyconfigs for SAMtools with different toolchains + some that use an external HTSlib (cfr. #1492)?

Other than the easyconfigs themselves, and the PRs through which they were added, there's no documentation.

**Comment by boegel** [comment]
@verdurin Should this still be open?

**Comment by verdurin** [comment]
It's fine to close this particular one, but I think we should agree on an approach of documenting variations like this. Otherwise it's a bit impenetrable for new users.
