### ISSUE TITLE
EasyConfig for BioKanga

### ISSUE THREAD

**Issue by nathanhaigh** [hpcugent/easybuild-easyconfigs#2246]
**BioKanga** is an integrated toolkit of high performance bioinformatics subprocesses targeting the challenges of next generation sequencing analytics. **Kanga** is an acronym standing for "K-mer Adaptive Next Generation Aligner".

http://sourceforge.net/projects/biokanga

**Comment by boegel** [comment]
@nathanhaigh: if you're planning to open a pull request, there's no need to open an issue as well; the pull request itself serves as an issue too, so you're only creating duplicate issues this way

Please close this, let's follow up in #2247
