### ISSUE TITLE
CrayPGI support

### ISSUE THREAD

**Issue by jgphpc** [hpcugent/easybuild-easyconfigs#2338]
Trying new easyconfig for PGI support => easyconfigs/c/CrayPGI/CrayPGI-5.2.82.eb

This is related to:
* https://github.com/hpcugent/easybuild-framework/issues/1536
* ~~https://github.com/hpcugent/easybuild-framework/pull/1342~~

This is my very first time doing this, apologies in advance if i am mistaking.

**Comment by boegel** [comment]
hpcugent/easybuild-framework#

**Comment by boegel** [comment]
let's follow up in #2927
