### ISSUE TITLE
Building GCC on to top of GCCCore

### ISSUE THREAD

**Issue by ocaisa** [hpcugent/easybuild-easyconfigs#2371]
There is a subtle issue with GCC on top of GCCCore, if you list GCCCore as a dep of GCC then the libs of GCCCore take precedence when you use GCC as a toolchain because of how `LD_LIBRARY_PATH` and the linker flags are set up. The solution is to set GCCCore as a build dep but this leads to a problem in a hierarchical scheme as you will not get the modulepath extension to access the binutils built with GCCCore. @geimer I think the solution would be to handle this special case in the naming scheme: if GCCCore is a build dep of GCC then add the GCCCore path extension to the module **header** (i.e., extend the path but don't load the module, this must be done before you load the GCCCore binutils so would need to go in the header).

I'm happy to implement next week.

**Comment by boegel** [comment]
@ocaisa ping?

**Comment by ocaisa** [comment]
Not sure where to go with this. I can probably do it in the naming scheme reasonably easily and make it work with the shipped HMNS but any other hierarchical scheme that people use would also need a patch. I don't think it's worth the effort and the potential headache. In the next release we are likely to move to GCCcore with GCC5 so by the time it would be in the release it would be obsolete (my understanding is both  PGI and Intel compilers both work with GCC5, the only blocker is CUDA which is still GCC4). I'm gonna close this.
