### ISSUE TITLE
 BFAST-0.7.0a-goolf-1.4.10 depends on GCC 4.7.2 which produces @itemx errors during compile

### ISSUE THREAD

**Issue by jprorama** [hpcugent/easybuild-easyconfigs#2507]
The goolf-1.4.10 toolchain uses GCC 4.7.2 which causes @itemx error during the build of documentation for GCC when building on CentOS 7x.

`./../gcc/doc/cppopts.texi:806: @itemx must follow @item`

This error was fixed in GCC 4.7.3:

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52903

The goolf toolchain for BFAST needs to be updated.

**Comment by boegel** [comment]
fixed with #2522, so good to close @jprorama?

**Comment by jprorama** [comment]
Yes.
