### ISSUE TITLE
Glib easyconfigs missing libxml2 dependency

### ISSUE THREAD

**Issue by nathanhaigh** [hpcugent/easybuild-easyconfigs#2636]
#2265 highlihted that recent versions of Glib easyconfigs might be missing a libxml2 dependency. Without it, the system installed libxml2 is used. Just waiting on build testing of that PR to confirm.

**Comment by boegel** [comment]
Let's follow this up in #2638; I prefer avoiding duplicate 'issues', but opening an issue first so this doesn't get forgotten is a good idea.

Thanks for tackling this yourself @nathanhaigh

**Comment by nathanhaigh** [comment]
Ugh, forgot I already opened an issue! Serve me right for working at 5am while feeding the baby!
