### ISSUE TITLE
some typos in dowload urls for latest Perl easyconfigs extensions

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-easyconfigs#2737]
https://github.com/hpcugent/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/Perl/Perl-5.22.1-foss-2016a.eb#L156

https://github.com/hpcugent/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/Perl/Perl-5.22.1-foss-2016a.eb#L408

https://github.com/hpcugent/easybuild-easyconfigs/blob/develop/easybuild/easyconfigs/p/Perl/Perl-5.22.1-foss-2016a.eb#L549

**Comment by pescobar** [comment]
fixed in PR https://github.com/hpcugent/easybuild-easyconfigs/pull/2738

**Comment by boegel** [comment]
Let's follow up in the PR
