### ISSUE TITLE
Trouble installing Python-2.7.11-foss-2016a

### ISSUE THREAD

**Issue by SimonPinches** [hpcugent/easybuild-easyconfigs#2776]
I have trouble to install `Python-2.7.11-foss-2016a` due to what I think is a `zlib` problem in `Tk/8.6.4-foss-2016a-no-X11`.

See this [log file](https://github.com/hpcugent/easybuild-easyconfigs/files/188815/easybuild-Tk-8.6.4-20160324.234408.iqUYd.log.txt) for more details.

**Comment by boegel** [comment]
Does including `zlib` in the list of dependencies for `Tk` (like it is for `Tcl` on which `Tk` depends already) help?

**Comment by SimonPinches** [comment]
Yes, this is fixed by #2778

**Comment by boegel** [comment]
OK, great, thanks for issuing the PR, please close this issue.

**Comment by SimonPinches** [comment]
Fixed and closed :-)
