### ISSUE TITLE
qt/4.8.6 dummy toolchain support

### ISSUE THREAD

**Issue by jgphpc** [hpcugent/easybuild-easyconfigs#2777]
Hi,
I (really) need to build qt/4.8 (for Cube, see [#941](https://github.com/hpcugent/easybuild-easyconfigs/issues/941)) with the dummy toolchain on Cray SLES/11.3 (=gcc/4.3).
Building it without easybuild:
```
http://download.qt.io/official_releases/qt/4.8/4.8.6/
./configure -opensource -nomake tests -nomake examples \
-confirm-license -release -shared -no-accessibility -no-sql-mysql -no-sql-sqlite
```
is ok but i have a conflict with easyblocks/q/qt.py if i try with eb/270:

[qt.py](https://github.com/hpcugent/easybuild-easyblocks/blob/master/easybuild/easyblocks/q/qt.py#L55)

Can you help me modify the easyblock ?

remark: gcc/43 is **NOT** compatible with qt/5.x
jg.

**Comment by boegel** [comment]
What problems are you running into exactly with the Qt easyblock?

Also, why do you need to build Qt with the `dummy` toolchain? Just asking because it complicates things, e.g. EasyBuild does *not* prepare the build environment (like defining `$CC`, `$CFLAGS`, etc.) for `dummy`...

**Comment by jgphpc** [comment]
Here is the output:
```
eb ./Qt-4.8.6.eb.ko
== temporary log file in case of crash /tmp/eb-XFiWCN/easybuild-6PWFzb.log
== processing EasyBuild easyconfig /users/piccinal/EB/pug.git/scorep/easybuild_easyconfigs/DORA/DUMMY/forscorep/Qt-4.8.6.eb.ko
== building and installing Qt/4.8.6...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== FAILED: Installation ended unsuccessfully 
(build directory: /dev/shm/piccinal/Qt/4.8.6/dummy-dummy): 


build failed (first 300 chars): Don't know which platform to set based on compiler family.


== Results of the build can be found in the log file /tmp/eb-XFiWCN/easybuild-Qt-4.8.6-20160325.082015.imoUh.log
ERROR: Build of /users/piccinal/EB/pug.git/scorep/easybuild_easyconfigs/
DORA/DUMMY/forscorep/Qt-4.8.6.eb.ko failed 
(err: "build failed (first 300 chars): Don't know which platform to set based on compiler family.")
```

* The message "Don't know which platform to set ..." is coming from [qt.py](https://github.com/hpcugent/easybuild-easyblocks/blob/master/easybuild/easyblocks/q/qt.py#L55)

We can discuss about the dummy toolchain.

**Comment by boegel** [comment]
OK, thanks for clarifying that; the Qt easyblock is indeed not compatible with the `dummy` toolchain right now.

What we should do is allow that you can do this in a Qt easyconfig file:

```
platform = 'linux-g++-64'
```

If the Qt easyblock sees that this is defined, it would use it without question rather than derive it based on the compiler toolchain.

So, the relevant block in the Qt easyblock should become something like:

```python
        platform = None
        comp_fam = self.toolchain.comp_family()
        if self.cfg['platform']:
            platform = self.cfg['platform']
        # if no platform is specified, try to derive it based on compiler in toolchain
        elif comp_fam in [toolchain.GCC]:  #@UndefinedVariable
            platform = 'linux-g++-64'
        elif comp_fam in [toolchain.INTELCOMP]:  #@UndefinedVariable
            platform = 'linux-icc-64'

        if platform:
            self.cfg.update('configopts', "-platform %s" % platform)
        else:
            raise EasyBuildError("Don't know which platform to set based on compiler family.")
```

To make sure that `platform = ...` is being picked up from the easyconfig file, you'll need to define the `extra_options` method in the `EB_Qt` class in the easyblock; something like:

```python
    @staticmethod
    def extra_options():
        extra_vars = {
            'platform': [None, "Target platform to build for (e.g. linux-g++-64, linux-icc-64)", CUSTOM],
        }
        return ConfigureMake.extra_options(extra_vars)
```

**Comment by boegel** [comment]
@jgphpc Thanks for looking into this in https://github.com/hpcugent/easybuild-easyblocks/pull/875 (which needs to be reopened since it's targeting `master` than `develop`, but fine).

I suggest we close this, and follow this up in your easyblocks PR?

**Comment by jgphpc** [comment]
> I suggest we close this, and follow this up in your easyblocks PR?
yes please close it.
