### ISSUE TITLE
Query as to whether CPATH is set correctly in the libxml2 modules

### ISSUE THREAD

**Issue by SimonPinches** [hpcugent/easybuild-easyconfigs#2783]
At present `CPATH=$EBROOTLIBXML2/include` in the `libxml2` modules but maybe it should be `CPATH=$EBROOTLIBXML2/include/libxml2`?

@boegel just helped me to create a fix for this problem in the easyconfig file for a library I needed to build (see #2787): `preconfigopts = 'export CFLAGS="$CFLAGS -I$EBROOTLIBXML2/include/libxml2 " && '` but maybe the fix should be to the `libxml2` modules?

(I admit though that I would have expected this problem, if it is one, to have previously come to light.)

**Comment by boegel** [comment]
fixed in https://github.com/hpcugent/easybuild-easyblocks/pull/981
