### ISSUE TITLE
tmux configopts

### ISSUE THREAD

**Issue by jgphpc** [hpcugent/easybuild-easyconfigs#2818]
Hi,

To build tmux using the dummy toolchain (Suse11), 
i have to:
```module load libutempter/1.1.6-3``` 
because i need $EBROOTLIBUTEMPTER for:
```configopts =  " LDFLAGS=-L$EBROOTLIBUTEMPTER/lib"```
although i would expect:
 ```builddependencies = [ ('libutempter', '1.1.6-3'), ]```
to set $EBROOTLIBUTEMPTER for me (without having to do the module load).

Thanks for any advice.

**Comment by pforai** [comment]
When you run eb with debug and logging do you see the libutemper module not being loaded? Can you post a gist of the log and link it here?

 `builddependencies[]` are loaded as modules at build time - the same as for normal dependencies. The only difference is that normal dependencies are for things that are need at run time of the application you're trying to build (say shared libraries and related things) and as such are rendered into the module file to be loaded if they are not already loaded while build dependencies are only loaded at build time for building and are not rendered into the module file.

**Comment by boegel** [comment]
@jgphpc for easyconfig that use the `dummy` toolchain and have (build) dependencies listed, you must use a non-`dummy` version in the toolchain specification, for example:

```python
toolchain = {'name': 'dummy', 'version': ''}
```

as opposed to

```python
toolchain = {'name': 'dummy', 'version': 'dummy'}
```

Using `dummy` as toolchain version has the side effect of not loading modules for (build) dependencies during the installation. There used to be a (somewhat) good reason for this, but today it's just weird behaviour.

This, and the somewhat strange name `dummy`, is a motivation to move away from `dummy` and replace with a `system` toolchain, cfr. https://github.com/hpcugent/easybuild-framework/pull/1233

**Comment by jgphpc** [comment]
Hi,

Thank you both for looking. I can confirm that ```version:''``` fixes the problem.
Thank you also for the system toolchain, i will try to use it from now on.

jg.
