### ISSUE TITLE
Better new-pr diagnostics

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-easyconfigs#2841]
I'm trying out `--new-pr` and I'm finding the error messages less than fully helpful.

E.g.

```
[adam@marcel IGVTools]$ eb --new-pr --pr-branch-name=igv-2.3.72 --pr-descr="Update IGVTools to 2.3.72" --pr-title="{bio} IGVTools-2.3.72" --github-user=verdurin
/usr/lib/python2.7/site-packages/keyring/backends/Gnome.py:6: PyGIWarning: GnomeKeyring was imported without specifying a version first. Use gi.require_version('GnomeKeyring', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GnomeKeyring
== temporary log file in case of crash /tmp/eb-NGDUT8/easybuild-_ayqzZ.log
ERROR: Experimental functionality. Behaviour might change/be removed later (use --experimental option to enable). Opening new pull request for:
```

For example, if I'm missing some of the mandatory options, EB should say so.

**Comment by verdurin** [comment]
Okay, after actually reading the error message properly, I tried again and now it says it's missing a path, but it's not clear to which path it's referring?

**Comment by boegel** [comment]
@verdurin update on this?

**Comment by verdurin** [comment]
@boegel - I think we've already covered this with some documentation changes. I was confused at the time because it didn't fit with the standard topic branch workflow.
