### ISSUE TITLE
kallisto MPI problem with foss-2016a

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-easyconfigs#2970]
I'm trying to build `kallisto` for `foss-2016a`.

There's an error at the linking stage relating to MPI, which is odd because `kallisto` doesn't use MPI...

[easybuild-kallisto-0.42.4-20160429.082510.iBfIV.log.txt](https://github.com/hpcugent/easybuild-easyconfigs/files/241931/easybuild-kallisto-0.42.4-20160429.082510.iBfIV.log.txt)

**Comment by boegel** [comment]
As mentioned by @rjeschmi on IRC, this is probably by using the parallel version of HDF5 as a dependency.

@verdurin can you try changing the HDF5 dep to the 'serial' variant?

**Comment by verdurin** [comment]
Thanks @rjeschmi and @boegel.

Fixed in https://github.com/hpcugent/easybuild-easyconfigs/pull/2979
