### ISSUE TITLE
MDSplus module doesn't set all required environment variables

### ISSUE THREAD

**Issue by SimonPinches** [hpcugent/easybuild-easyconfigs#3026]

**Comment by boegel** [comment]
@SimonPinches there's no need to open an issue if you're planning on opening a PR too (unless you want a reminder-to-self centrally)

fixed in #3027, let's follow-up there

**Comment by SimonPinches** [comment]
I was trying to follow the instructions for contributing but agree that it appeared unnecessary to open an issue.
