### ISSUE TITLE
Kent_tools depends upon libpng12

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-easyconfigs#3196]
Binaries from the `Kent_tools` easyconfig depend upon version 1.12 of `libpng`.

At least on Fedora/CentOS, this can be met by installing `libpng12`.

**Comment by verdurin** [comment]
In further testing, 245 of the files in the `bin` directory rely on `libpng12`.

**Comment by verdurin** [comment]
Attempt to address this in https://github.com/hpcugent/easybuild-easyconfigs/pull/3197

**Comment by boegel** [comment]
let's follow up in #3197, thanks @verdurin!
