### ISSUE TITLE
Wrong setting of environmental variables in Geant4

### ISSUE THREAD

**Issue by lekshmideepu** [hpcugent/easybuild-easyconfigs#3213]
Since I wanted to download the data sets, I modified the easy config (Geant4-10.02.p01-intel-2016a.eb) by adding the below lines:

```
configopts += " -DGEANT4_INSTALL_DATA=ON "

G4ABLAVersion = '3.0'
G4NDLVersion = '4.5'
G4EMLOWVersion = '6.48'
PhotonEvaporationVersion = '3.2'
G4RadioactiveDecayVersion = '4.3'
```

The path of the below environmental variables are shown as follows after the installation.

```
setenv("G4LIB","/usr/local/software/../Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/lib64/Geant4")
setenv("G4LEVELGAMMADATA","/usr/local/software/../Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.02.1/data/PhotonEvaporation
3.2")
setenv("G4RADIOACTIVEDATA","/usr/local/software/../Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.02.1/data/RadioactiveDecay
4.3")
setenv("G4LEDATA","/usr/local/software/../Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.02.1/data/G4EMLOW6.48")
setenv("G4NEUTRONHPDATA","/usr/local/software/../Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.02.1/data/G4NDL4.5")
```

The above shown path `/usr/local/software/../Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.02.1/ ` doesn't exists. Instead, the actual path that exists is `/usr/local/software/../Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.2.1/`

```
-bash-4.2$ ls /usr/local/software/../Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.02.1/data/
ls: cannot access /usr/local/software/../Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.02.1/data/: No such file or directory

-bash-4.2$ ls /usr/local/software/../Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.2.1/data/
G4ABLA3.0    G4ENSDFSTATE1.2.1  G4NEUTRONXS1.4  G4SAIDDATA1.1         RadioactiveDecay4.3.1
G4EMLOW6.48  G4NDL4.5           G4PII1.3        PhotonEvaporation3.2  RealSurface1.0
```

**Comment by boegel** [comment]
@lekshmideepu Thanks for reporting this issue!

It seems like this is a small bug in the Geant4 easyblock, cfr. https://github.com/hpcugent/easybuild-easyblocks/blob/351a94f171cc1da9ccfc543f77389c9ce6aa38fd/easybuild/easyblocks/g/geant4.py#L273 .

Basically, rather than using the 'official' version `10.02.p01`, this is being used as a subdirectory: `10.2.1`.

As you can tell, we are currently already stripping off the `p0`, but we're not stripping off the leading zero `0`...

Is there a clear mapping between the official version and the name of the subdirectory, i.e. is that documented somewhere?

**Comment by lekshmideepu** [comment]
Thanks for the response @boegel 
I couldn't find any documentation for the mapping between the official version and the name of the subdirectory.
I found the following info [here](http://geant4.web.cern.ch/geant4/UserDocumentation/UsersGuides/InstallationGuide/html/ch03s03.html)

_On Windows platforms, you will need to download and unpack them by hand to the location you specified for GEANT4_INSTALL_DATADIR. If you did not set this, it defaults to CMAKE_INSTALL_PREFIX/share/Geant4-10.2.0/data. Unpacking the datasets in this location will result in Geant4 automatically locating them once geant4.(c)sh or geant4make.(c)sh have been sourced._

**Comment by lekshmideepu** [comment]
Some moe information in [this](http://geant4.web.cern.ch/geant4/UserDocumentation/UsersGuides/InstallationGuide/html/ch02.html) link.

 _*WARNING*
      Geant4 has been pre-configured to look for datasets
      in the directory:
      /path/to/geant4.10.2-install/share/Geant4-10.2.0/data_

**Comment by boegel** [comment]
@lekshmideepu This should be fixed in the updated easyblock in https://github.com/hpcugent/easybuild-easyblocks/pull/961, please verify?

You can use the updated easyblock by:

* downloading it from https://raw.githubusercontent.com/boegel/easybuild-easyblocks/07c35a0a8382e1efa4c22278a201662e47f7da3f/easybuild/easyblocks/g/geant4.py
* using `eb --include-easyblocks /path/to/updated/geant4.py ...`

**Comment by lekshmideepu** [comment]
Thanks for the quick response. Still there are some minor issues.
1. Added "space" before the second option of "configopts" in easy config file. Otherwise the build was successful, but no "data" folder exists.
2. Now data folder exists :-)
-bash-4.2$ ls /usr/local/software/../Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.2.1/data/
G4ABLA3.0    G4ENSDFSTATE1.2.1  G4NEUTRONXS1.4  G4SAIDDATA1.1         RadioactiveDecay4.3.1
G4EMLOW6.48  G4NDL4.5           G4PII1.3        PhotonEvaporation3.2  RealSurface1.0

Env. variables are as follows: 
 setenv("G4LEVELGAMMADATA","PhotonEvaporation3.2")
setenv("G4RADIOACTIVEDATA","/usr/local/software/jureca/Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.2.1/data/RadioactiveDecay4.3")
setenv("G4LEDATA","/usr/local/software/jureca/Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.2.1/data/G4EMLOW6.48")
setenv("G4NEUTRONHPDATA","/usr/local/software/jureca/Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.2.1/data/G4NDL4.5")
Issues:
-bash-4.2$ ls $G4LEVELGAMMADATA
ls: cannot access PhotonEvaporation3.2: No such file or directory
-bash-4.2$ echo $G4LEVELGAMMADATA
PhotonEvaporation3.2
Note: But this folder exists

-bash-4.2$ ls $G4RADIOACTIVEDATA
ls: cannot access /usr/local/software/jureca/Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.2.1/data/RadioactiveDecay4.3: No such file or directory
Note: But ...../data/RadioactiveDecay4.3.1/ exists.

$G4NEUTRONHPDATA and $G4LEDATA are showing the expected results!

**Comment by boegel** [comment]
@lekshmideepu the space issue is already fixed in https://github.com/hpcugent/easybuild-easyconfigs/pull/3209

The problem with `$G4LEVELGAMMADATA` is a bug in the updated easyblock, I've fixed this in https://github.com/hpcugent/easybuild-easyblocks/pull/961 just now, see https://github.com/hpcugent/easybuild-easyblocks/pull/961/commits/9c35ebbfb58d740e72590df65098b645a6404259

The problem with `$G4RADIOACTIVEDATA` is because you should specify `4.3.1` as version in the easyconfig file, i.e.:

```python
G4RadioactiveDecayVersion = '4.3.1'
```

**Comment by boegel** [comment]
@lekshmideepu the updated Geant4 easyblock has been merged and will be part of the next EasyBuild release (v2.8.2)

unless there's something else that hasn't been tackled yet, please close this issue?

**Comment by lekshmideepu** [comment]
Thanks for the fixes @boegel I will test this and close the issue.

**Comment by lekshmideepu** [comment]
There is again a minor issue with G4LEVELGAMMADATA

Instead of 
```
setenv("G4LEVELGAMMADATA","/usr/local/software/jureca/Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.2.1/data/PhotonEvaporation3.2")
```
 it shows the following.
```
setenv("G4LEVELGAMMADATA","PhotonEvaporation/usr/local/software/jureca/Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.2.1/data/3.2")
```
Contents of data folder is as follows:
```
ls /usr/local/software/jureca/Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.2.1/data/
G4ABLA3.0    G4ENSDFSTATE1.2.1  G4NEUTRONXS1.4  G4SAIDDATA1.1         RadioactiveDecay4.3.1
G4EMLOW6.48  G4NDL4.5           G4PII1.3        PhotonEvaporation3.2  RealSurface1.0
```
Other variables are showing the expected values.
```
setenv("G4RADIOACTIVEDATA","/usr/local/software/jureca/Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.2.1/data/RadioactiveDecay4.3.1")
setenv("G4LEDATA","/usr/local/software/jureca/Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.2.1/data/G4EMLOW6.48")
setenv("G4NEUTRONHPDATA","/usr/local/software/jureca/Stage1/software/Geant4/10.02.p01-GCC-4.9.3-2.25/share/Geant4-10.2.1/data/G4NDL4.5")
```

**Comment by boegel** [comment]
@lekshmideepu urgh, ok, thanks for reporting this, I fixed this in https://github.com/hpcugent/easybuild-easyblocks/pull/970

**Comment by lekshmideepu** [comment]
Thanks @boegel :+1: :+1:
