### ISSUE TITLE
Update HMMER source_urls, possibly use github, etc etc

### ISSUE THREAD

**Issue by fgeorgatos** [hpcugent/easybuild-easyconfigs#3242]
Most EasyBuilders need no introduction to what `source_urls`'s churn rate is; 

HMMER was just added to the pile and now requires:
* wget http://eddylab.org/software/hmmer3/3.0/hmmer-3.0-linux-intel-x86_64.tar.gz

So, either the easyconfigs now require an update or, *there is a better way*:
* For each and every software that now lives on github, use the following construct:
  * source_urls = ['https://github.com/alexdobin/STAR/archive/'] # kudos for the one doing that
  * fi. https://github.com/EddyRivasLab/hmmer/tree/3.0 exists

Going that way is a marvel, because you could now feed a git commit ID at `--try-software-version`!

In fact, this might prove to be such a better approach that it might be worthy of its own templating:
https://github.com/hpcugent/easybuild-framework/blob/9a6df6828bd2e484318afe02d06eb6372f939bfa/easybuild/framework/easyconfig/templates.py#L91
(if so, this should become a framework issue; great advantage: no need to do that much checksums!)

@caylo: Looking for a worthy challenge? ;-)

p.s. 
Permit me stop the ranting here or, I will start on http://www.cython.org/release/ being down today ;-)

**Comment by boegel** [comment]
@fgeorgatos for Cython, see https://github.com/hpcugent/easybuild-easyconfigs/pull/3212

That being said, we're always going to be at the mercy of upstream changing things (or screwing things up, cfr. https://bitbucket.org/pypa/pypi/issues/438/backwards-compatible-un-hashed-package)...

**Comment by boegel** [comment]
fixed in #3246, follow-up there please
