### ISSUE TITLE
wrong source spec in HMMER easyconfigs

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild-easyconfigs#3313]
all HMMER easyconfigs contain:

```
sources = ['hmmer-%(version)s-linux-intel-x86_64.tar.gz']
```

so even though it's being installed on top of a particular toolchain, we're actually just installing a binary build?

thoughts @rjeschmi, @pescobar, @verdurin?

**Comment by boegel** [comment]
thoughts @fgeorgatos, @rjeschmi, @pescobar, @verdurin?

**Comment by verdurin** [comment]
@boegel - yes, the current situation is a bit misleading. I would prefer a proper source version, as well as this binary one.

**Comment by fgeorgatos** [comment]
yes, +1, fully agreed with @verdurin ; fyi. if I recall right, the 1st cases here came by @xaver42 !

**Comment by fgeorgatos** [comment]
addendum: @xaver42 contributed the following, which also includes the patchfile:
https://github.com/hpcugent/easybuild-easyconfigs/commit/517eebedfdf77fe3456d1e17e0746c2ff0ed24d1

The verdict is still the same: the ones which are not true source builds may need versionsuffix;
the patch itself, kind of implies that the makefile actually does some kind of *source* build
(i'm not opening the tarball now, but someone *should* before a change of this type is applied)

**Comment by boegel** [comment]
Fixed in #4531

It seems like the actual building maybe indeed be happening all along, but since we're starting from a source tarball that already includes binaries who knows... Starting from a clean source tarball is certainly better.

@fgeorgatos The patch is only relevant to HMMER v3.1b1.
