### ISSUE TITLE
Too much time for Installing Amber14

### ISSUE THREAD

**Issue by rtripath89** [hpcugent/easybuild-easyconfigs#3404]
I am trying to install Amber14, but it has been more then 16 hours and it seems stuck at install step. It hasn't thrown up any errors, and seems to be still running. I was wondering if you guys know how much time does it take for Amber's installation via Easconfig, as this seems like a really long time.

**Comment by akesandgren** [comment]
Haven't tried installing with EB (yet) but a outside-EB build of Amber should take <3h (value should be grossly overestimated)

**Comment by rtripath89** [comment]
Well, it never finished, so I had to cancel the installation. Do you guys have any suggestions, if I am going wrong somewhere or might need to change something for the installation to complete?

**Comment by rtripath89** [comment]
Hi, I investigated a bit more by using --logtostdout flag, and it looks like it configures properly but doesn't start the next step ' make install':

![image](https://cloud.githubusercontent.com/assets/17620535/17681907/029dc33e-630e-11e6-99f4-2e85e7dd249e.png)

This is where it seems to hang

**Comment by rtripath89** [comment]
It built properly.

**Comment by boegel** [comment]
@rtripath89 did you change anything to make it install properly? Any idea why it was hanging?

**Comment by rtripath89** [comment]
@boegel : I am not really sure what was happening. for 2-2.5 weeks, it kept hanging after configure step and never moved to 'make install' part, but 2 days back it built. As far as I can see at this point, there doesn't seem to be anything different in the environment.

**Comment by rtripath89** [comment]
Atleast we know that Easybuild framework wasn't the problem. 👍
