### ISSUE TITLE
libxml2 depends on liblzma

### ISSUE THREAD

**Issue by akesandgren** [hpcugent/easybuild-easyconfigs#3408]
If the system has the development package for liblzma installed the build of libxlm2 will have dependencies on lzma_<functions>. The static libxml2.a will not have these resolved and thus building, for instance, GROMACS will fail with unresolved symbols.

I think libxml2 should either depend on lzma (better choice) or forcibly disable lzma (not as good).

**Comment by boegel** [comment]
@akesandgren adding lzma (`XZ`) as a dependency for libxml2 is fine by me to avoid that it's being picked up from the OS

I also considered this recently, but I ran into a blocker: XZ (which provides `liblzma`) depends on `gettext`, which in turn depends on `libxml2`. So including `XZ` as a dep for `libxml2` would introduce a cyclic dep.

We're probably missing something here, like one of these actually only being a build dep or something like that...

**Comment by akesandgren** [comment]
gettext is only a builddep for XZ, so this should be doable.

**Comment by akesandgren** [comment]
xz doesn't need gettext to conf/build "correctly" (it will simply lack language support for its messages), so a bootstrap xz that doesn't have a builddep on gettext (may use the system gettext binaries if installed, which they almost always are) that can then be used to build libxml2 -> gettext -> xz

Another way would be to start with a bootstrap libxml2 without lzma support, and then take the chain forward.

And by bootstrap i of course mean using dummy toolchain.

**Comment by akesandgren** [comment]
I currently have no libxml2, gettext, or XZ installed (by easybuild).
A bit of config writing gives me the following chain, does it look sane?

b-an03 [easybuild]$ eb libxml2-2.9.4-foss-2016b.eb --dry-run 
== temporary log file in case of crash /scratch/ake/tmp/eb-vzcjwj/easybuild-AXT1fx.log
Dry run: printing build status of easyconfigs and dependencies
 * [ ] /pfs/nobackup/home/a/ake/eb-tree/ebfiles_repo/l/libxml2/libxml2-2.9.4.eb (module: libxml2/2.9.4)
 * [x] /eb/opt/easybuild_repo/M4/M4-1.4.17.eb (module: M4/1.4.17)
 * [ ] /eb/common/software/EasyBuild/2.8.2/lib/python2.7/site-packages/easybuild_easyconfigs-2.8.2-py2.7.egg/easybuild/easyconfigs/a/Autoconf/Autoconf-2.69.eb (module: Autoconf/2.69)
 * [ ] /eb/common/software/EasyBuild/2.8.2/lib/python2.7/site-packages/easybuild_easyconfigs-2.8.2-py2.7.egg/easybuild/easyconfigs/a/Automake/Automake-1.15.eb (module: Automake/1.15)
 * [x] /eb/opt/easybuild_repo/GCCcore/GCCcore-5.4.0.eb (module: GCCcore/5.4.0)
 * [x] /eb/opt/easybuild_repo/GCC/GCC-5.4.0-2.26.eb (module: GCC/5.4.0-2.26)
 * [x] /eb/opt/easybuild_repo/OpenBLAS/OpenBLAS-0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.1.eb (module: OpenBLAS/0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.1)
 * [ ] /eb/common/software/EasyBuild/2.8.2/lib/python2.7/site-packages/easybuild_easyconfigs-2.8.2-py2.7.egg/easybuild/easyconfigs/l/libtool/libtool-2.4.6.eb (module: libtool/2.4.6)
 * [ ] /eb/opt/easybuild_repo/ncurses/ncurses-6.0.eb (module: ncurses/6.0)
 * [ ] /eb/common/software/EasyBuild/2.8.2/lib/python2.7/site-packages/easybuild_easyconfigs-2.8.2-py2.7.egg/easybuild/easyconfigs/a/Autotools/Autotools-20150215.eb (module: Autotools/20150215)
 * [ ] /pfs/nobackup/home/a/ake/eb-tree/ebfiles_repo/g/gettext/gettext-0.19.8.eb (module: gettext/0.19.8)
 * [ ] /pfs/nobackup/home/a/ake/eb-tree/ebfiles_repo/x/XZ/XZ-5.2.2-GCC-5.4.0-2.26.eb (module: XZ/5.2.2-GCC-5.4.0-2.26)
 * [x] /eb/opt/easybuild_repo/numactl/numactl-2.0.11-GCC-5.4.0-2.26.eb (module: numactl/2.0.11-GCC-5.4.0-2.26)
 * [x] /eb/opt/easybuild_repo/hwloc/hwloc-1.11.3-GCC-5.4.0-2.26.eb (module: hwloc/1.11.3-GCC-5.4.0-2.26)
 * [x] /eb/opt/easybuild_repo/OpenMPI/OpenMPI-1.10.3-GCC-5.4.0-2.26.eb (module: OpenMPI/1.10.3-GCC-5.4.0-2.26)
 * [x] /eb/opt/easybuild_repo/gompi/gompi-2016b.eb (module: gompi/2016b)
 * [x] /eb/opt/easybuild_repo/FFTW/FFTW-3.3.4-gompi-2016b.eb (module: FFTW/3.3.4-gompi-2016b)
 * [x] /eb/opt/easybuild_repo/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2016b-OpenBLAS-0.2.18-LAPACK-3.6.1.eb (module: ScaLAPACK/2.0.2-gompi-2016b-OpenBLAS-0.2.18-LAPACK-3.6.1)
 * [x] /eb/opt/easybuild_repo/foss/foss-2016b.eb (module: foss/2016b)
 * [ ] /pfs/nobackup/home/a/ake/eb-tree/ebfiles_repo/l/libxml2/libxml2-2.9.4-foss-2016b.eb (module: libxml2/2.9.4-foss-2016b)

**Comment by akesandgren** [comment]
And with minimal-toolchains=False the chain looks likes this:

b-an03 [easybuild]$ eb libxml2-2.9.4-foss-2016b.eb --dry-run
== temporary log file in case of crash /scratch/ake/tmp/eb-_EGzRv/easybuild-PJS0
xY.log
Dry run: printing build status of easyconfigs and dependencies
 * [x] /eb/opt/easybuild_repo/M4/M4-1.4.17.eb (module: M4/1.4.17)
 * [x] /eb/opt/easybuild_repo/GCCcore/GCCcore-5.4.0.eb (module: GCCcore/5.4.0)
 * [x] /eb/opt/easybuild_repo/GCC/GCC-5.4.0-2.26.eb (module: GCC/5.4.0-2.26)
 * [x] /eb/opt/easybuild_repo/OpenBLAS/OpenBLAS-0.2.18-GCC-5.4.0-2.26-LAPACK-3.6
.1.eb (module: OpenBLAS/0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.1)
 * [x] /eb/opt/easybuild_repo/numactl/numactl-2.0.11-GCC-5.4.0-2.26.eb (module: 
numactl/2.0.11-GCC-5.4.0-2.26)
 * [x] /eb/opt/easybuild_repo/hwloc/hwloc-1.11.3-GCC-5.4.0-2.26.eb (module: hwlo
c/1.11.3-GCC-5.4.0-2.26)
 * [x] /eb/opt/easybuild_repo/OpenMPI/OpenMPI-1.10.3-GCC-5.4.0-2.26.eb (module: 
OpenMPI/1.10.3-GCC-5.4.0-2.26)
 * [x] /eb/opt/easybuild_repo/gompi/gompi-2016b.eb (module: gompi/2016b)
 * [ ] /eb/common/software/EasyBuild/2.8.2/lib/python2.7/site-packages/easybuild
_easyconfigs-2.8.2-py2.7.egg/easybuild/easyconfigs/a/Autoconf/Autoconf-2.69.eb (
module: Autoconf/2.69)
 * [x] /eb/opt/easybuild_repo/FFTW/FFTW-3.3.4-gompi-2016b.eb (module: FFTW/3.3.4-gompi-2016b)
 * [x] /eb/opt/easybuild_repo/ScaLAPACK/ScaLAPACK-2.0.2-gompi-2016b-OpenBLAS-0.2.18-LAPACK-3.6.1.eb (module: ScaLAPACK/2.0.2-gompi-2016b-OpenBLAS-0.2.18-LAPACK-3.6.1)
 * [x] /eb/opt/easybuild_repo/foss/foss-2016b.eb (module: foss/2016b)
 * [ ] /eb/common/software/EasyBuild/2.8.2/lib/python2.7/site-packages/easybuild_easyconfigs-2.8.2-py2.7.egg/easybuild/easyconfigs/m/M4/M4-1.4.17-foss-2016b.eb (module: M4/1.4.17-foss-2016b)
 * [ ] /eb/common/software/EasyBuild/2.8.2/lib/python2.7/site-packages/easybuild_easyconfigs-2.8.2-py2.7.egg/easybuild/easyconfigs/l/libtool/libtool-2.4.6-foss-2016b.eb (module: libtool/2.4.6-foss-2016b)
 * [ ] /pfs/nobackup/home/a/ake/eb-tree/ebfiles_repo/n/ncurses/ncurses-6.0-foss-2016b.eb (module: ncurses/6.0-foss-2016b)
 * [ ] /eb/common/software/EasyBuild/2.8.2/lib/python2.7/site-packages/easybuild_easyconfigs-2.8.2-py2.7.egg/easybuild/easyconfigs/a/Autoconf/Autoconf-2.69-foss-2016b.eb (module: Autoconf/2.69-foss-2016b)
 * [ ] /eb/common/software/EasyBuild/2.8.2/lib/python2.7/site-packages/easybuild_easyconfigs-2.8.2-py2.7.egg/easybuild/easyconfigs/a/Automake/Automake-1.15-foss-2016b.eb (module: Automake/1.15-foss-2016b)
 * [ ] /eb/common/software/EasyBuild/2.8.2/lib/python2.7/site-packages/easybuild_easyconfigs-2.8.2-py2.7.egg/easybuild/easyconfigs/a/Autotools/Autotools-20150215-foss-2016b.eb (module: Autotools/20150215-foss-2016b)
 * [ ] /eb/common/software/EasyBuild/2.8.2/lib/python2.7/site-packages/easybuild_easyconfigs-2.8.2-py2.7.egg/easybuild/easyconfigs/a/Automake/Automake-1.15.eb (module: Automake/1.15)
 * [ ] /pfs/nobackup/home/a/ake/eb-tree/ebfiles_repo/l/libxml2/libxml2-2.9.4.eb (module: libxml2/2.9.4)
 * [ ] /eb/common/software/EasyBuild/2.8.2/lib/python2.7/site-packages/easybuild_easyconfigs-2.8.2-py2.7.egg/easybuild/easyconfigs/l/libtool/libtool-2.4.6.eb (module: libtool/2.4.6)
 * [ ] /eb/opt/easybuild_repo/ncurses/ncurses-6.0.eb (module: ncurses/6.0)
 * [ ] /eb/common/software/EasyBuild/2.8.2/lib/python2.7/site-packages/easybuild_easyconfigs-2.8.2-py2.7.egg/easybuild/easyconfigs/a/Autotools/Autotools-20150215.eb (module: Autotools/20150215)
 * [ ] /pfs/nobackup/home/a/ake/eb-tree/ebfiles_repo/g/gettext/gettext-0.19.8.eb (module: gettext/0.19.8)
 * [ ] /pfs/nobackup/home/a/ake/eb-tree/ebfiles_repo/x/XZ/XZ-5.2.2.eb (module: XZ/5.2.2)
 * [ ] /pfs/nobackup/home/a/ake/eb-tree/ebfiles_repo/l/libxml2/libxml2-2.9.4-GCC-5.4.0-2.26-XZ-5.2.2.eb (module: libxml2/2.9.4-GCC-5.4.0-2.26-XZ-5.2.2)
 * [ ] /pfs/nobackup/home/a/ake/eb-tree/ebfiles_repo/g/gettext/gettext-0.19.8-foss-2016b.eb (module: gettext/0.19.8-foss-2016b)
 * [ ] /pfs/nobackup/home/a/ake/eb-tree/ebfiles_repo/x/XZ/XZ-5.2.2-foss-2016b.eb (module: XZ/5.2.2-foss-2016b)
 * [ ] /pfs/nobackup/home/a/ake/eb-tree/ebfiles_repo/l/libxml2/libxml2-2.9.4-foss-2016b.eb (module: libxml2/2.9.4-foss-2016b)

**Comment by akesandgren** [comment]
Should it be done like this instead?
libxml2 (--without-lzma, dummy toolchain) -> gettext (using libxml2-without-lzxa, dummy-toolchain) -> xz (with the previous 2, dummy-toolchain) -> libxml2-with-lzma (still using dummy toolchain) -> gettext (using the previous libxml2) -> xz (using the previous 2, all with dummy toolchain) -> using the last 3 to build toolchain versions.

Or perhaps changing the last XZ above to bbe built with the required toolchain and the libxml2 -> gettext to depend on that XZ?

There is no end to the complexity one can create with a cyclic dependency :-)

**Comment by boegel** [comment]
@akesandgren why build the `libxml2` with lzma support also with `dummy`? why not straigt jump to a proper toolchain using the 'crippled' libxml2/xz that was built with `dummy` to bootstrap the whole thing?

also: what a mess... :)

how is this handled elsewhere, I can't help but wonder...

**Comment by akesandgren** [comment]
In other places all dev libs already exist (since they have been bootstrapped back in the good old days or so), so there is no longer a problem.

Bootstrapping from scratch now is awkward.

I thought about doing that too, but i wasn't sure where to jump to a proper toolchain.
How much of the xz dependency in libxml2 is "visible" in gettext?
How much of the libxml2 dependency in gettext is visible in xz?
And finally how much of the gettext dependency in xz is visible in libxml2?

If we could figure that out somehow, I could write up a "correct" chain.

If I do libxml2(without xz, dummy-toolchain) -> gettext(dummy-toolchain) -> xz(dummy-toolchain) I could jump to proper-toolchain-libxml2(with dummy-built-xz) and leave it at that.

It is also probably doable to start with xz(dummy-toolchain-without-eb-gettext) and let it pull in system-gettext if it exists (and ignore if it doesn't) and build proper-toolchain-libxml2 from that.

xz's dependency on gettext is mainly for creating i18n message texts (and reading them) but if it's only used for bootstrapping it shouldn't matter that much. But it may still affect the proper-toolchain-libxml2 when it uses that crippled-xz.

So, any thoughts on which way to go here?

**Comment by boegel** [comment]
@akesandgren sorry for the long delay in getting back to you on this... I would try and see how the last option works out, i.e.:

* dummy xz using system gettext (or not, whatever)
* toolchain libxml2 using dummy xz
* toolchain gettext + xz on top of this libxml2

**Comment by akesandgren** [comment]
That seems to work and makes it a minimal change to the .eb files.

I'll make a PR out of this.

**Comment by boegel** [comment]
@akesandgren great, thanks!

Once the PR is there, please close this issue.

**Comment by akesandgren** [comment]
Added PR 3568. Closing the issue.
