### ISSUE TITLE
Bug in python string format of h5py package

### ISSUE THREAD

**Issue by timeu** [hpcugent/easybuild-easyconfigs#3484]
Shuld be: `versionsuffix = '-Python-%(pyver)s-HDF5-%s' % hdf5ver` instead of `versionsuffix = '-Python-%%(pyver)s-HDF5-%s' % hdf5ver`

https://github.com/hpcugent/easybuild-easyconfigs/commit/623cc278c4037beb3540263441840a834b152116#diff-9f53eb89c91c407e3c44b7c2191322efR19

**Comment by boegel** [comment]
@timeu no, what's there is actually correct...

The thing is that `%(pyver)s` is a template that is filled in by EasyBuild at some point, i.e. when the dependency versions are available after parsing the whole easyconfig file

This:

```python
hdf5ver = '1.8.16'
versionsuffix = '-Python-%%(pyver)s-HDF5-%s' % hdf5ver
```

gets translated to this when the easyconfig file is being parsed (well, before actually, when it's picked up for parsing, sort of):

```
versionsuffix = '-Python-%(pyver)s-HDF5-1.8.16'
```

The double `%` in `%%(pyver)s` is there to escape the `%`, such that the template `%(pyver)s` is left intact.

The only reason `hdf5ver` is being used is as a local variable in the easyconfig file itself (to avoid copy-pasting the '1.8.16' in multiple places).

Let me know if that's clear...

**Comment by timeu** [comment]
@boegel: Yeah this makes sense. Sorry for the opening an invalid issue
