### ISSUE TITLE
Broken alias in VirSorter easyconfig

### ISSUE THREAD

**Issue by bedroge** [hpcugent/easybuild-easyconfigs#3565]
As described in the closed PR #3307, the %(namelower)s in the modaliases (as was suggested by @boegel) does not get replaced in the actual module file, causing errors when trying to load the module. Should this be done in a different way, or is this a bug in the framework?

**Comment by boegel** [comment]
@bedroge Thanks for opening a separate issue for this.

I don't see anything wrong with how you're using `%(namelower)s`, so this looks like a bug in the framework, I'll take a closer look at this.

**Comment by boegel** [comment]
@bedroge you're indeed hitting a bug in the framework, fixed in https://github.com/hpcugent/easybuild-framework/pull/1904, thanks for reporting this!
