### ISSUE TITLE
EB 2.9, GCCcore-6.2.0 wrong URL

### ISSUE THREAD

**Issue by jhein32** [hpcugent/easybuild-easyconfigs#3605]
Hi,

The GCCcore-6.2.0 is using a bad URL for downloading sources.  According to extended-dry-run it is using

    http://ftpmirror.gnu.org/gcccore/gcccore-6.2.0/$source

Playing around with mozilla shows

    http://ftpmirror.gnu.org/gcc/gcc-6.2.0/$source

might be the correct thing.  I can see the source at

    http://ftp.acc.umu.se/mirror/gnu.org/gnu/gcc/gcc-6.2.0/

I fixed myself using a manual download.

Joachim

**Comment by boegel** [comment]
Thanks for reporting this @jhein32! Fixed in #3608
