### ISSUE TITLE
Add support for Amber 16

### ISSUE THREAD

**Issue by edmondac** [hpcugent/easybuild-easyconfigs#3659]
Amber 16 is out (http://ambermd.org/#Amber16). Include .eb file and updated patch.

**Comment by edmondac** [comment]
I've done the work for this... just not sure how to assign it to myself...

**Comment by edmondac** [comment]
Just fighting with the CUDA build, then we'll be done.

**Comment by boegel** [comment]
fixed in #3688, thanks @edmondac!
