### ISSUE TITLE
GCCCore-6.2.0 wrong url

### ISSUE THREAD

**Issue by sguera** [hpcugent/easybuild-easyconfigs#3676]
The url where to download from is wrong:

 'http://ftpmirror.gnu.org/%(namelower)s/%(namelower)s-%(version)s',

is only working in a GCC-whatever.eb

Here it searchs for:
http://ftpmirror.gnu.org/gcccore/gcccore-6.2.0/gcc-6.2.0.tar.bz2

and does not find it.

That line should be:

 'http://ftpmirror.gnu.org/gcc/gcc-%s' % version,

**Comment by boegel** [comment]
@sguera this is fixed in `develop` via https://github.com/hpcugent/easybuild-easyconfigs/pull/3608
