### ISSUE TITLE
Java-1.8.0_92 not working

### ISSUE THREAD

**Issue by shahzebsiddiqui** [hpcugent/easybuild-easyconfigs#3743]
Source file not found. Seems like Java is updating their files, we might need to find a proper url to download archived versions. Seems like latest release is 111 and 112 according to 

http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

[hpcswadm@hpcv18 Java]$ eb Java-1.8.0_92.eb
== temporary log file in case of crash /hpc/grid/scratch/tmp/eb-DU6HB_/easybuild-bKFeBy.log
== processing EasyBuild easyconfig /nfs/grid/software/RHEL7-BUILD/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.9.0-py2.7.egg/easybuild/easyconfigs/j/Java/Java-1.8.0_92.eb
== building and installing Java/1.8.0_92...
== fetching files...
== FAILED: Installation ended unsuccessfully (build directory: /nfs/grid/software/RHEL7-BUILD/easybuild/build/Java/1.8.0_92/dummy-dummy): build failed (first 300 chars): Couldn't find file jdk-8u92-linux-x64.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order): /nfs/grid/software/RHEL7-BUILD/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.9.0-py2.7.egg/easybuild/easyconfigs/j/Java/j/Java/jdk-8u92-linux-x64
== Results of the build can be found in the log file(s) /hpc/grid/scratch/tmp/eb-DU6HB_/easybuild-Java-1.8.0_92-20161028.143655.XibBk.log
ERROR: Build of /nfs/grid/software/RHEL7-BUILD/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.9.0-py2.7.egg/easybuild/easyconfigs/j/Java/Java-1.8.0_92.eb failed (err: "build failed (first 300 chars): Couldn't find file jdk-8u92-linux-x64.tar.gz anywhere, and downloading it didn't work either... Paths attempted (in order): /nfs/grid/software/RHEL7-BUILD/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.9.0-py2.7.egg/easybuild/easyconfigs/j/Java/j/Java/jdk-8u92-linux-x64")

**Comment by boegel** [comment]
@shahzebsiddiqui EasyBuild can't auto-download Java for you because it requires agreeing to the license.

There *is* an archive for older Java versions though, it's just hidden well, see http://www.oracle.com/technetwork/java/javase/downloads/java-archive-javase8-2177648.html#jdk-8u92-oth-JPR
