### ISSUE TITLE
X11-20160819 libXft build error

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-easyconfigs#3748]
Saw this error when building X11-20160819-foss-2016b:

```
checking whether make supports nested variables... (cached) yes
checking for XRENDER... yes
checking for FREETYPE... configure: error: Package requirements (freetype2 >= 2.1.6) were not met:

Package 'bzip2', required by 'freetype2', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables FREETYPE_CFLAGS
and FREETYPE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

**Comment by boegel** [comment]
@verdurin fixed with #3464?

**Comment by jinchang** [comment]
I have the same issue. Is this issue fixed or is there any work around?

Thank you.

**Comment by Helios07** [comment]
I struggeled about the same error and found a workaround.
In the file __your_install_prefix_/freetype/2.6.5/lib/pkgconfig/freetype2.pc I had to remove the harfbuzz dependency, after that X11 was completely compiled (I and harfbuzz and harfbuzz-devel installed on the system).

**Comment by boegel** [comment]
follow-up on the missing HarfBuzz dependency in #4596
