### ISSUE TITLE
Issue building GCC-4.7.2.eb

### ISSUE THREAD

**Issue by SethosII** [hpcugent/easybuild-easyconfigs#3819]
When I run BLAT-3.5-goolf-1.4.10.eb like `eb --buildpath=/dev/shm --module-syntax=Lua --modules-tool=Lmod --optarch=march=corei7 --parallel=4 BLAT-3.5-goolf-1.4.10.eb -dr` it fails at the building-step of GCC-4.7.2.eb.

Here is the output of the command:

```
== temporary log file in case of crash /tmp/eb-qmebZt/easybuild-kZpQqg.log
== resolving dependencies ...
== processing EasyBuild easyconfig /easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.9.0-py2.7.egg/easybuild/easyconfigs/g/GCC/GCC-4.7.2.eb
== building and installing GCC/4.7.2...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== FAILED: Installation ended unsuccessfully (build directory: /dev/shm/GCC/4.7.2/dummy-dummy): build failed (first 300 chars): cmd " make -j 4  bootstrap " exited with exitcode 2 and output:
echo stage3 > stage_final
make[1]: Entering directory `/run/shm/GCC/4.7.2/dummy-dummy/gcc-4.7.2/obj'
make[2]: Entering directory `/run/shm/GCC/4.7.2/dummy-dummy/gcc-4.7.2/obj'
make[2]: Leaving directory `/run/shm/GCC/4.7.2/dummy-dummy/g
== Results of the build can be found in the log file(s) /tmp/eb-qmebZt/easybuild-GCC-4.7.2-20161117.105227.IFpvF.log
ERROR: Build of /easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_easyconfigs-2.9.0-py2.7.egg/easybuild/easyconfigs/g/GCC/GCC-4.7.2.eb failed (err: 'build failed (first 300 chars): cmd " make -j 4  bootstrap " exited with exitcode 2 and output:\necho stage3 > stage_final\nmake[1]: Entering directory `/run/shm/GCC/4.7.2/dummy-dummy/gcc-4.7.2/obj\'\nmake[2]: Entering directory `/run/shm/GCC/4.7.2/dummy-dummy/gcc-4.7.2/obj\'\nmake[2]: Leaving directory `/run/shm/GCC/4.7.2/dummy-dummy/g')
```

The last lines of the log file are these:

```
../../gcc/doc/cppopts.texi:806: @itemx must follow @item
make[3]: *** [doc/cpp.info] Error 1
make[3]: *** Waiting for unfinished jobs....
../../gcc/doc/install.texi:3143: warning: @anchor should not appear in @heading

...

../../gcc/doc/service.texi:6: warning: node up `Service' in menu `Bugs' and in sectioning `Top' differ
make[3]: *** [doc/gcc.info] Error 1
rm gcc.pod
make[3]: Leaving directory `/run/shm/GCC/4.7.2/dummy-dummy/gcc-4.7.2/obj/gcc'
make[2]: *** [all-stage1-gcc] Error 2
make[2]: Leaving directory `/run/shm/GCC/4.7.2/dummy-dummy/gcc-4.7.2/obj'
make[1]: *** [stage1-bubble] Error 2
make[1]: Leaving directory `/run/shm/GCC/4.7.2/dummy-dummy/gcc-4.7.2/obj'
make: *** [bootstrap] Error 2
 (at easybuild/software/EasyBuild/2.9.0/lib/python2.7/site-packages/easybuild_framework-2.9.0-py2.7.egg/easybuild/tools/run.py:438 in parse_cmd_output)
== 2016-11-17 10:53:46,640 easyblock.py:2380 WARNING build failed (first 300 chars): cmd " make -j 4  bootstrap " exited with exitcode 2 and output:
echo stage3 > stage_final
make[1]: Entering directory `/run/shm/GCC/4.7.2/dummy-dummy/gcc-4.7.2/obj'
make[2]: Entering directory `/run/shm/GCC/4.7.2/dummy-dummy/gcc-4.7.2/obj'
make[2]: Leaving directory `/run/shm/GCC/4.7.2/dummy-dummy/g
== 2016-11-17 10:53:46,640 easyblock.py:269 INFO Closing log for application name GCC version 4.7.2
```

The same issue occures when building GCC-4.7.2.eb alone.

Up to now I couldn't find something usefull for this error message. Does anyone else encounter the same issue and how can I get more Information to fix this?

I'm using EasyBuild 2.9.0.

**Comment by boegel** [comment]
@SethosII Which operating system (and version) are you using here?

It looks this (old) GCC version may not be compatible with your (recent) OS...

The error messages seem to suggest it has something to do with the GCC documentation that can't be built, which may relate to the LaTeX version you have provided by the OS.

Do you really need this old GCC version, or are you mainly interested in BLAT?

If it's the latter, I would suggest that you try with a different, more recent toolchain than `goolf-1.4.10`, for example as follows:

```
# replace the trailing ... with your additional options
eb BLAT-3.5-goolf-1.4.10.eb --try-toolchain foss,2016b --robot ...
```

Furthermore, there's no need to specify `--parallel` yourself, EasyBuild will use all available cores provided by your system by default.
Also, the `--optarch` spec you provide may not be what you want; EasyBuild optimises specifically for the system you are building on by default, see http://easybuild.readthedocs.io/en/latest/Controlling_compiler_optimization_flags.html.

**Comment by SethosII** [comment]
Hey @boegel, I'm running a Ubuntu Server 14.04.5. The version problematic seems plausible.

I'm mainly interested in BLAT. The `--try-toolchain` option works, thanks!

The other options are used for some other reasons. `--parallel` because the server is also used by other people and shouldn't be occupied solely by me and `--optarch` is needed because the software should run on different servers with different architectures (and building the software for each different architecture is not desired). But nevertheless thank you for the suggestions!

**Comment by boegel** [comment]
@SethosII great! For more information on `--try-*`, see http://easybuild.readthedocs.io/en/latest/Using_the_EasyBuild_command_line.html?highlight=try-toolchain#tweaking-existing-easyconfig-files-using-try
