### ISSUE TITLE
Matlab R2016b

### ISSUE THREAD

**Issue by shahzebsiddiqui** [hpcugent/easybuild-easyconfigs#3848]
Hello,

We are having issues building Matlab. If i understand we need to install some toolbox according to https://github.com/hpcugent/easybuild-easyconfigs/tree/master/easybuild/easyconfigs/m/MATLAB

I don't know which one needs to be installed and how to install them.

Could you please assist us in this matter.

-bash-4.2$ eb MATLAB-2016b.eb
== temporary log file in case of crash /hpc/grid/scratch/sreeka01/tmp/eb-Bx3zvF/easybuild-S5v1bg.log
== processing EasyBuild easyconfig /hpc/grid/scratch/sreeka01/matlab/MATLAB-2016b.eb
== building and installing MATLAB/2016b...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== postprocessing...
== sanity checking...
== FAILED: Installation ended unsuccessfully (build directory: /hpc/grid/scratch/sreeka01/build/MATLAB/2016b/dummy-): build failed (first 300 chars): Sanity check failed: no file of ('bin/matlab',) in /hpc/grid/scratch/sreeka01/easybuild/software/MATLAB/2016b, no file of ('bin/mcc',) in /hpc/grid/scratch/sreeka01/easybuild/software/MATLAB/2016b, no file of ('bin/glnxa64/MATLAB',) in /hpc/grid/scratch/sreeka01/easybuild/software/MATLAB/2016b, no f
== Results of the build can be found in the log file /hpc/grid/scratch/sreeka01/tmp/eb-Bx3zvF/easybuild-MATLAB-2016b-20161117.122946.Gzxlv.log
ERROR: Build of /hpc/grid/scratch/sreeka01/matlab/MATLAB-2016b.eb failed (err: "build failed (first 300 chars): Sanity check failed: no file of ('bin/matlab',) in /hpc/grid/scratch/sreeka01/easybuild/software/MATLAB/2016b, no file of ('bin/mcc',) in /hpc/grid/scratch/sreeka01/easybuild/software/MATLAB/2016b, no file of ('bin/glnxa64/MATLAB',) in /hpc/grid/scratch/sreeka01/easybuild/software/MATLAB/2016b, no f")
-bash-4.2$ less /hpc/grid/scratch/sreeka01/tmp/eb-Bx3zvF/easybuild-MATLAB-2016b-20161117.122946.Gzxlv.log

**Comment by boegel** [comment]
@shahzebsiddiqui Did you check the log file for errors w.r.t. the license key/server?

You need to specify a correct license key (and maybe also server/port) to make the installation work, by editing the easyconfig file you are using and correcting the `license_server`, `license_server_port` and `key` values.

If not, the log will show something like:

```
(Dec 03, 2016 12:58:33) Error: You have entered an invalid File Installation Key.
(Dec 03, 2016 12:58:33) Exiting with status -1
(Dec 03, 2016 12:58:34) End - Unsuccessful
```

**Comment by shahzebsiddiqui** [comment]
I don't know how to download the toolbox separately from Matlab. When I install MATLAB R2016b zip file it comes with the base install. If you run the install script, it pulls in the toolbox from mathworks. I am trying to figure out how to get them installed locally.

**Comment by boegel** [comment]
@shahzebsiddiqui I don't think the sanity check includes a check for any toolboxes... The README just shows the files list as it is for the MATLAB install files provided to us.

**Comment by shahzebsiddiqui** [comment]
Hi Ken,

Can we do a google hangout and I can show what the issue is.

What time works for you?

Regards,

**Comment by boegel** [comment]
@shahzebsiddiqui It would be easier if you make a full debug log available for us to look into...

**Comment by shahzebsiddiqui** [comment]
Strange, now it seems to work. I tried passing debug option and nothing changed on the system and it worked. I guess you can close this ticket.
