### ISSUE TITLE
Problems with impi for intel-2016b

### ISSUE THREAD

**Issue by andreas-h** [hpcugent/easybuild-easyconfigs#3869]
Not sure if this is the correct place to report this issue ...

I have this impi easyconfig (modified from EB3.0.0 for different source file and our license server):

     This is an easyconfig file for EasyBuild, see http://hpcugent.github.io/easybuild
    
    name = 'impi'
    version = '5.1.3.181'
    
    homepage = 'http://software.intel.com/en-us/intel-mpi-library/'
    description = """The Intel(R) MPI Library for Linux* OS is a multi-fabric message
     passing library based on ANL MPICH2 and OSU MVAPICH2. The Intel MPI Library for
     Linux OS implements the Message Passing Interface, version 2 (MPI-2) specification."""
    
    toolchain = {'name': 'iccifort', 'version': '2016.3.210-GCC-5.4.0-2.26'}
    
    sources = ['parallel_studio_xe_2016_update3.tgz']
    
    checksums = ['eda19bb0d0d19709197ede58f13443f3']
    
    dontcreateinstalldir = 'True'
    
    components = ['intel-mpi', 'intel-psxe', 'intel-imb']
    
    license_file = '28518@10.103.15.186'
    
    # set up all the mpi commands to default to intel compilers
    # set_mpi_wrappers_all = 'True'
    
    postinstallcmds = [
        'ln -s %(installdir)s/lib64/libmpi.so  %(installdir)s/lib64/libmpich.so',
        'ln -s %(installdir)s/lib64/libmpigc4.so  %(installdir)s/lib64/libmpichcxx.so',
        'ln -s %(installdir)s/lib64/libmpigf.so %(installdir)s/lib64/libfmpich.so',
        'ln -s %(installdir)s/lib64/libmpigf.so %(installdir)s/lib64/libmpichf90.so',
        'ln -s %(installdir)s/lib64/libmpi.so %(installdir)s/lib64/libmpl.so',
        'ln -s %(installdir)s/lib64/libmpi.so %(installdir)s/lib64/libopa.so'
    ]
    
    moduleclass = 'mpi'

Now, when I try to install, I get the following error:

    == 2016-11-29 18:05:18,296 run.py:443 INFO cmd "./install.sh  -s /dev/shm/eb-build/impi/5.1.3.181/iccifort-2016.3.210-GCC-5.4.0-2.26/parallel_studio_xe_2016_update3/silent.cfg" exited with exitcode 0 and output:
    Missing optional prerequisites
    -- Unsupported OS
    --------------------------------------------------------------------------------
    
    == 2016-11-29 18:05:18,327 build_log.py:149 ERROR EasyBuild crashed with an error (at ?:124 in __init__): Failed to move contents of /opt/software/eb/software/impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26/impi/5.1.3.181 to /opt/software/eb/software/impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26: [Errno 2] No such file or directory: '/opt/software/eb/software/impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26/impi/5.1.3.181' (at easybuild/easyblocks/generic/intelbase.py:366 in move_after_install)
    == 2016-11-29 18:05:18,328 easyblock.py:2498 WARNING build failed (first 300 chars): Failed to move contents of /opt/software/eb/software/impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26/impi/5.1.3.181 to /opt/software/eb/software/impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26: [Errno 2] No such file or directory: '/opt/software/eb/software/impi/5.1.3.181-iccifort-2016.3.210-GCC
    == 2016-11-29 18:05:18,328 easyblock.py:276 INFO Closing log for application name impi version 5.1.3.181
    == 2016-11-29 18:05:18,329 easyblock.py:276 INFO Closing log for application name impi version 5.1.3.181
    == 2016-11-29 18:05:18,329 build_log.py:220 INFO FAILED: Installation ended unsuccessfully (build directory: /dev/shm/eb-build/impi/5.1.3.181/iccifort-2016.3.210-GCC-5.4.0-2.26): build failed (first 300 chars): Failed to move contents of /opt/software/eb/software/impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26/impi/5.1.3.181 to /opt/software/eb/software/impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26: [Errno 2] No such file or directory: '/opt/software/eb/software/impi/5.1.3.181-iccifort-2016.3.210-GCC
    == 2016-11-29 18:05:18,329 build_log.py:220 INFO Results of the build can be found in the log file(s) /tmp/eb-cJUotz/easybuild-impi-5.1.3.181-20161129.175752.KaUOo.log
    == 2016-11-29 18:05:18,330 build_log.py:149 ERROR EasyBuild crashed with an error (at ?:124 in __init__): build failed (first 300 chars): Failed to move contents of /opt/software/eb/software/impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26/impi/5.1.3.181 to /opt/software/eb/software/impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26: [Errno 2] No such file or directory: '/opt/software/eb/software/impi/5.1.3.181-iccifort-2016.3.210-GCC (at easybuild/main.py:118 in build_and_install_software)
    == 2016-11-29 18:05:18,331 build_log.py:149 ERROR EasyBuild crashed with an error (at ?:124 in __init__): Build of /home/lamos1/hilboll/impi-5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26.eb failed (err: "build failed (first 300 chars): Failed to move contents of /opt/software/eb/software/impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26/impi/5.1.3.181 to /opt/software/eb/software/impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26: [Errno 2] No such file or directory: '/opt/software/eb/software/impi/5.1.3.181-iccifort-2016.3.210-GCC") (at easybuild/main.py:150 in build_and_install_software)

This is a CentOS7.2 system.

It seems to me that at some point, there's the GCC version string missing from some directory name, but after looking into the move_after function in the intelbase easyblock, I don't see how this could possibly be the case ...

**Comment by boegel** [comment]
@andreas-h can you share a full (debug) log for this?

**Comment by andreas-h** [comment]
here it is: https://gist.github.com/anonymous/45f9a8a9b3bb5047cefa8e68ed437f1a

**Comment by boegel** [comment]
@andreas-h is the `/opt/software/eb/software/impi/5.1.3.181-iccifort-2016.3.210-GCC-5.4.0-2.26/impi/5.1.3.181` directory actually there?

There's nothing going on with a missing GCC version in a directory name, you're just looking at a partial error (only the first 300 chars are shown...).

Any chance you had two `impi` installations running at the same time, where one is stamping on the feet of another?

If not, can you check whether the install logs created by the Intel installer somewhere in `/tmp` give you any clues?
The "unsupported OS" is just a warning you can ignore, but maybe the installation really failed, and there *is* no directory to move at all...

Maybe this is a licensing issue?

**Comment by andreas-h** [comment]
Sorry, that was a very stupid mistake on my side.  I had tried to
install from the parallel_studio_xe_2016_update3.tgz file, but that
actually includes impi-5.1.3.210, and not impi-5.1.3.181.  So no, the
correct directory was actually missing.

I'm now downloading the MPI tarball for 5.1.3.181, and assume that all
my problems will be gone then ...

Sorry for the noise, and thanks a lot for your continuous effort in
helping me out of my stupid mistakes ...

**Comment by boegel** [comment]
@andreas-h no problem, been there before ;)

In that case, let's close this issue?
