### ISSUE TITLE
OpenPGM source not found

### ISSUE THREAD

**Issue by andreas-h** [hpcugent/easybuild-easyconfigs#3935]
When building `OpenPGM-5.2.122-intel.2016a`, the source tar cannot be found:

> == 2016-12-16 00:05:03,176 filetools.py:349 WARNING URL http://openpgm.googlecode.com/files/libpgm-5.2.122.tar.gz was not found (HTTP response code 404), not trying again

**Comment by boegel** [comment]
@andreas-h this is fixed in https://github.com/hpcugent/easybuild-easyconfigs/pull/3930/files#diff-e524140136628a877e183d975b5bfc36

**Comment by andreas-h** [comment]
thanks, @boegel !
