### ISSUE TITLE
GCC doesn't build in Centos7 when "multilib = True"

### ISSUE THREAD

**Issue by pescobar** [hpcugent/easybuild-easyconfigs#3964]
I cannot build `GCC/4.7.2` or `GCC/4.8.4` in Centos 7.2 when I use the option `multilib = True` in the GCC easyconfigs. These easyconfigs work fine in Centos 6

The error message is quite cryptic and I couldn't figure out the reason of the crash.

```
make[3]: Leaving directory `/scratch/easybuild/generic/GCC/4.7.2/dummy-dummy/gcc-4.7.2/obj/build-x86_64-unknown-linux-gnu/libiberty'
make[2]: Leaving directory `/scratch/easybuild/generic/GCC/4.7.2/dummy-dummy/gcc-4.7.2/obj'
make[1]: *** [stage1-bubble] Error 2
make[1]: Leaving directory `/scratch/easybuild/generic/GCC/4.7.2/dummy-dummy/gcc-4.7.2/obj'
make: *** [bootstrap] Error 2
```

Here you can see some build logs:

Easybuild log: https://gist.github.com/anonymous/98dff6c9e96b08d167a045d360de95bc

config.log in the GCC build dir: https://gist.github.com/anonymous/9cfa77a6d5d65d94aea5da0fbe8838fb

config.log in the GMP build dir: https://gist.github.com/anonymous/383bd74b54837cfc20ef32c3d60b7a33

**Comment by boegel** [comment]
@pescobar does building GCC with `eb --parallel 1` help to pinpoint the issue?

From the EasyBuild log:

```
configure: error: Link tests are not allowed after GCC_NO_EXECUTABLES.
...
make[2]: *** [configure-stage1-zlib] Error 1
```

That seems to be the actual error, but you'll need to figure out the right `config.log` to get more information about what's going wrong exactly...

This seems to be relevant, maybe you have some package missing to support multilib builds?

**Comment by pescobar** [comment]
You are right @boegel , I was missing some libs

After compiling with `eb --parallel 1` this is the error message:

```
checking whether the gcc  -m32 linker (ld -m elf_x86_64 -m elf_i386) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... configure: error: Link tests are not allowed after GCC_NO_EXECUTABLES.
make[2]: *** [configure-stage1-zlib] Error 1
make[2]: Leaving directory `/scratch/easybuild-user/builds/GCC/4.8.4/dummy-dummy/gcc-4.8.4/obj'
make[1]: *** [stage1-bubble] Error 2
make[1]: Leaving directory `/scratch/easybuild-user/builds/GCC/4.8.4/dummy-dummy/gcc-4.8.4/obj'
make: *** [bootstrap] Error 2
 (at easybuild/apps/EasyBuild/3.0.2/lib/python2.6/site-packages/easybuild_framework-3.0.2-py2.6.egg/easybuild/tools/run.py:438 in parse_cmd_output)
== 2017-01-03 14:41:14,571 easyblock.py:2503 WARNING build failed (first 300 chars): cmd " make -j 1  bootstrap " exited with exitcode 2 and output:
echo stage3 > stage_final
```

I have solved it by doing `yum -y install glibc-devel.i686 libstdc++-devel.i686` . Now GCC builds correctly

**Comment by boegel** [comment]
@pescobar we should enhance the GCC easyblock to spit out a meaningful error in case those packages are not installed?

**Comment by pescobar** [comment]
@boegel I think it would be helpful for sure because the error is quite cryptic and it took me some time to figure out what was the problem
