### ISSUE TITLE
formatting of modloadmsg

### ISSUE THREAD

**Issue by SethosII** [hpcugent/easybuild-easyconfigs#4013]
I came around several modules (mostly Java stuff) that lack a new line after the message and which display a backslah before the `$EBROOT`:

```
modloadmsg = """To execute GATK run: java -jar \\$EBROOTGATK/GenomeAnalysisTK.jar"""
```

or

```
modloadmsg = "To execute picard run: java -jar \\${EBROOTPICARD}/%(name)s.jar"
```

So when loaded the output looks like this:

```
user@computer:~$ module load picard
To execute picard run: java -jar \${EBROOTPICARD}/picard.jaruser@computer:~$
```

So there is a bogus backslash, the curly braces are unnecessary, and a line break at the end of the message is missing.

Is there some reasoning behind this or is something wrong with the parsing of `modloadmsg` or is it just a remenant of previous easyconfig syntax which is now changed?

**Comment by boegel** [comment]
@SethosII The escaping of `$` is no longer needed since EasyBuild v1.16.0 (Dec'14), see https://github.com/hpcugent/easybuild-framework/pull/1068 .

The missing line break is probably something that got overlooked.

So, feel free to fix these issues if you run into them.

**Comment by SethosII** [comment]
@boegel Thanks for the explanation. I will do so.

Can you also tell me what's the deal with the tripple quotes (`"""`)? And the curly braces are also unnecessary from my understanding?

**Comment by boegel** [comment]
the triple quotes are used for strings that include newlines

curly braces should indeed not be needed

**Comment by SethosII** [comment]
@boegel Thanks for the explanation.
