### ISSUE TITLE
XZ 5.2.2 breaks rpm command on CentOS 7.3

### ISSUE THREAD

**Issue by boegel** [hpcugent/easybuild-easyconfigs#4036]
The build of Python fails because the `openssl-devel` OS dep is not found, even though it's installed, due to:

```
rpm: /apps/gent/CO7/sandybridge/software/XZ/5.2.2-intel-2016b/lib/liblzma.so.5: version `XZ_5.1.2alpha' not found (required by /lib64/librpmio.so.3)
```

There's a patch available for XZ 5.2.2 that fixes this issue (it was applied to the `xz` shipped with RHEL7.3):

```diff
We provided two 5.1.2alpha symbols (lzma_stream_encoder_mt and
lzma_stream_encoder_mt_memusage) before we updated to xz-5.2.2-1 in RHEL7.3.

Those symbols did not change ABI in 5.2.2 so it should be safe to provide
(except for 5.0 and 5.2 symbols) also the two 5.1.2alpha symbols and
use 5.1.2alpha symbol version as parent for 5.2.

For better reasoning look at container.h in 5.1.2alpha -- those two symbols
were for testing purposes only, and thus not considered to be API/ABI.

diff --git a/src/liblzma/liblzma.map b/src/liblzma/liblzma.map
index f53a4ea..9c3002a 100644
--- a/src/liblzma/liblzma.map
+++ b/src/liblzma/liblzma.map
@@ -95,7 +95,13 @@ global:
 	lzma_vli_size;
 };
 
-XZ_5.2 {
+XZ_5.1.2alpha {
+global:
+	lzma_stream_encoder_mt;
+	lzma_stream_encoder_mt_memusage;
+} XZ_5.0;
+
+XZ_5.2.2 {
 global:
 	lzma_block_uncomp_encode;
 	lzma_cputhreads;
@@ -105,4 +111,4 @@ global:
 
 local:
 	*;
-} XZ_5.0;
+} XZ_5.1.2alpha;
```

**Comment by boegel** [comment]
fixed in #4179, let's follow-up there

**Comment by Jadamso** [comment]
I am having this issue with XZ 5.2.3 on Scientific Linux 7.3

any help would be appreciated

**Comment by boegel** [comment]
@Jadamso You should reinstall XZ 5.2.3 with EasyBuild v3.1.1 or more recent, we included a patch for XZ to fix this problem.

**Comment by Jadamso** [comment]
How do I do that?

I have installed easybuild
     pip install --install-option "--prefix=$HOME/EasyBuild" easybuild

But this installation ...
    vers=5.2.3
    wget "http://tukaani.org/xz/xz-$vers.tar.gz"
    tar xzvf xz-$vers.tar.gz && rm xz-$vers.tar.gz
    cd ~/xz-$vers
    ./configure --prefix=$HOME 
    make
    sudo make install

Has broken yum

**Comment by boegel** [comment]
@Jadamso If you are not using EasyBuild to install XZ, you can apply the patch you can find in https://github.com/easybuilders/easybuild-easyconfigs/pull/4179/files#diff-252ec2c8e1bfeed0c2cbc6ea7f538a6c

**Comment by Pratheesh99** [comment]
how to update this patch on linux server using putty ?
