### ISSUE TITLE
TBB

### ISSUE THREAD

**Issue by verdurin** [hpcugent/easybuild-easyconfigs#4123]
This is a tracking issue to cover the desire for a free software build of Threaded Building Blocks, as mentioned on the mailing list.

This is required for the most recent release of `Bowtie2`.

**Comment by boegel** [comment]
see thread at https://lists.ugent.be/wws/arc/easybuild/2017-01/msg00071.html

**Comment by boegel** [comment]
fixed in #4538 and #4541, using updated easyblock from https://github.com/hpcugent/easybuild-easyblocks/pull/1168, included in EasyBuild v3.2.0
