### ISSUE TITLE
CP2K-4.1-foss-2016b-psmp.eb build fail

### ISSUE THREAD

**Issue by fedepad** [hpcugent/easybuild-easyconfigs#4191]
Hi,

I'm using EasyBuild 3.1.0.
OS is Scientific Linux: 2.6.32-504.30.3.el6.x86_64,
System python: 2.6.6
System gcc: 4.4.7

I tried to build/install CP2K, in particular easyconfig: CP2K-4.1-foss-2016b-psmp.eb
The build fail at (terminal output):

> == COMPLETED: Installation ended successfully
> == Results of the build can be found in the log file(s) /gpfs/iowraptest/software_manager/easybuild_installation/software/zlib/1.2.8/easybuild/easybuild-zlib-1.2.8-20170223.110507.log
> == processing EasyBuild easyconfig /gpfs/iowraptest/software_manager/easybuild_installation/software/EasyBuild/3.1.0/lib/python2.6/site-packages/easybuild_easyconfigs-3.1.0-py2.6.egg/easybuild/easyconfigs/b/binutils/binutils-2.26.eb
> == building and installing binutils/2.26...
> == fetching files...
> == creating build dir, resetting environment...
> == unpacking...
> == patching...
> == preparing...
> == configuring...
> == building...
> == testing...
> == installing...
> == taking care of extensions...
> == postprocessing...
> == sanity checking...
> == cleaning up...
> == creating module...
> == permissions...
> == packaging...
> == COMPLETED: Installation ended successfully
> == Results of the build can be found in the log file(s) /gpfs/iowraptest/software_manager/easybuild_installation/software/binutils/2.26/easybuild/easybuild-binutils-2.26-20170223.110753.log
> == processing EasyBuild easyconfig /gpfs/iowraptest/software_manager/easybuild_installation/software/EasyBuild/3.1.0/lib/python2.6/site-packages/easybuild_easyconfigs-3.1.0-py2.6.egg/easybuild/easyconfigs/g/GCCcore/GCCcore-5.4.0.eb
> == building and installing GCCcore/5.4.0...
> == fetching files...
> == creating build dir, resetting environment...
> == unpacking...
> == patching...
> == preparing...
> == configuring...
> == building...
> == FAILED: Installation ended unsuccessfully (build directory: /gpfs/iowraptest/software_manager/easybuild_buildpath/GCCcore/5.4.0/dummy-): build failed (first 300 chars): cmd " make -j 8 " exited with exitcode 2 and output:
> make[1]: Entering directory `/gpfs/iowraptest/software_manager/easybuild_buildpath/GCCcore/5.4.0/dummy-/gcc-5.4.0/stage1_obj'
> mkdir -p -- ./fixincludes
> mkdir -p -- ./libiberty
> mkdir -p -- ./lto-plugin
> mkdir -p -- ./gmp
> mkdir -p -- ./intl
> Configuri
> == Results of the build can be found in the log file(s) /tmp/eb-GPgfOV/easybuild-GCCcore-5.4.0-20170223.110753.BlSzf.log
> ERROR: Build of /gpfs/iowraptest/software_manager/easybuild_installation/software/EasyBuild/3.1.0/lib/python2.6/site-packages/easybuild_easyconfigs-3.1.0-py2.6.egg/easybuild/easyconfigs/g/GCCcore/GCCcore-5.4.0.eb failed (err: 'build failed (first 300 chars): cmd " make -j 8 " exited with exitcode 2 and output:\nmake[1]: Entering directory `/gpfs/iowraptest/software_manager/easybuild_buildpath/GCCcore/5.4.0/dummy-/gcc-5.4.0/stage1_obj\'\nmkdir -p -- ./fixincludes\nmkdir -p -- ./libiberty\nmkdir -p -- ./lto-plugin\nmkdir -p -- ./gmp\nmkdir -p -- ./intl\nConfiguri') 

I attach also 
[easybuild-GCCcore-5.4.0-20170223.110753.BlSzf.txt](https://github.com/hpcugent/easybuild-easyconfigs/files/796187/easybuild-GCCcore-5.4.0-20170223.110753.BlSzf.txt)

the log for debugging help. The problem seems to appear when finishing GCCcore-5.4.0 build.

**Comment by wpoely86** [comment]
This seems bad:
```
checking for C compiler default output file name... checking for C compiler default output file name... 
checking for suffix of object files... 
configure: error: in `/gpfs/iowraptest/software_manager/easybuild_buildpath/GCCcore/5.4.0/dummy-/gcc-5.4.0/stage1_obj/x86_64-unknown-linux-gnu/libatomic':
configure: error: C compiler cannot create executables
See `config.log' for more details.
checking for suffix of object files... configure: error: in `/gpfs/iowraptest/software_manager/easybuild_buildpath/GCCcore/5.4.0/dummy-/gcc-5.4.0/stage1_obj/x86_64-unknown-linux-gnu/libgomp':
configure: error: C compiler cannot create executables
See `config.log' for more details.
```
Can you have a look at why it fails (see `config.log`)?

**Comment by fedepad** [comment]
Attached here so anyone can see it.
[config_err_log.txt](https://github.com/hpcugent/easybuild-easyconfigs/files/796289/config_err_log.txt)

**Comment by wpoely86** [comment]
```
ld.gold: error: /gpfs/iowraptest/software_manager/easybuild_buildpath/GCCcore/5.4.0/dummy-/gcc-5.4.0/stage1_obj/./gcc/libgcc_s.so:1:1: invalid character
```
That's new for me.

Any chance that you could try to build it on a regular filesystem (non gpfs)? It might be unrelated but I would like to rule it out for certain.

**Comment by fedepad** [comment]
I waited for the build to finish before notifying you. 
The build ended successfully when changing the buildpath to a local FS. This is somehow odd...or?

**Comment by wpoely86** [comment]
Not really. We have seen it on multiple occasions that building on a network filesystem can lead to weird behaviour. It's difficult to find out exactly what goes wrong. It can be that the filesystem is not quick enough and by the time you go looking, it's all back fine. Especially `configure` scripts are prone to this as they create and delete a lot of small files very quickly.

I advise to put the build dir on a local filesystem.

**Comment by boegel** [comment]
+1 on the latter, it's heavily recommended to use a local directory as build directory

If this answer your question @fedepad, please close this issue
