### ISSUE TITLE
Wrong variable in easybuild-easyconfigs/easybuild/easyconfigs/g/GDAL/GDAL-2.1.2-intel-2016b-Python-2.7.12.eb?

### ISSUE THREAD

**Issue by klust** [hpcugent/easybuild-easyconfigs#4264]
Shouldn't
--with-jpeg=$EBROOTLIBJPEGTURBO
be
--with-jpeg=$EBROOTLIBJPEGMINTURBO
?? Or is there a configuration parameter in EasyBuild that influences how module names are translated in EBROOT variables so that the easyconfig is correct for some but not for all EasyBuild configurations?

The consequence of this mistake is that GDAL switches to an internal jpeg implementation, so jpeg support is still present and the error can remain unnoticed.

**Comment by wpoely86** [comment]
Yes, that's a typo. Can you send a PR to fix it?

**Comment by klust** [comment]
Done.

**Comment by boegel** [comment]
fixed in #4276 by @klust, thanks!
