### ISSUE TITLE
FFTW 3.3.6-pl1 has broken Fortran03 interface files

### ISSUE THREAD

**Issue by akesandgren** [hpcugent/easybuild-easyconfigs#4284]
The F03 interface to FFTW 3.3.6 is broken, lots of function definitions are missing.

There is a maintainer mode patch in their git that solves this.

I have a run that maintainer build and have a patch under testing right now.

Unless fftw 3.3.6-pl2 comes out before the next EB release this is a mandatory update for all toolchains that uses FFTW 3.3.6

**Comment by boegel** [comment]
@akesandgren To be clear, this is a bug in FFTW 3.3.6-pl1 itself, not an issue with how we install it with EasyBuild?

Can you include a pointer to the patch you mentioned?

**Comment by akesandgren** [comment]
Yes, it's a bug in FFTW itself.

The commit is: https://github.com/FFTW/fftw3/commit/83092f8efbf872aefe7cfc6ee8fa43412f8e167a
But that is only a maintainer mode patch and not usable in an easyconfig.
But, as i said above, i have run that stuff and have a patch that can be applied.

**Comment by akesandgren** [comment]
Patch works.

**Comment by boegel** [comment]
proposed fix in #4334

**Comment by boegel** [comment]
fixed in #4334, to be included with EasyBuild v3.1.2
