### ISSUE TITLE
Sanity check in Mesa is wrong

### ISSUE THREAD

**Issue by damianam** [hpcugent/easybuild-easyconfigs#4352]
It checks for `include/GL/wglext.h` which is not installed nor necessary, according to https://github.com/mesa3d/mesa/commit/3511a86111866f7233a337a24c9c6442b9aa05e6

**Comment by wpoely86** [comment]
ok, drop it than?

**Comment by damianam** [comment]
Ask and you shall receive. Maybe ;-): https://github.com/hpcugent/easybuild-easyconfigs/pull/4354

**Comment by boegel** [comment]
Wait, the Mesa sanity check has always passed for us, so that file is there? What am I missing?

```
$ find software/Mesa -name wglext.h
software/Mesa/11.2.1-foss-2016a/include/GL/wglext.h
software/Mesa/11.1.2-intel-2016a/include/GL/wglext.h
software/Mesa/11.0.2-intel-2015b-Python-2.7.10/include/GL/wglext.h
software/Mesa/11.1.2-foss-2016a/include/GL/wglext.h
software/Mesa/11.0.8-intel-2015b-Python-2.7.11/include/GL/wglext.h
software/Mesa/11.1.2-gimkl-2.11.5/include/GL/wglext.h
software/Mesa/12.0.2-foss-2016b/include/GL/wglext.h
software/Mesa/12.0.2-intel-2016b/include/GL/wglext.h
software/Mesa/11.2.1-intel-2016a/include/GL/wglext.h
```

**Comment by damianam** [comment]
Yes, the file was copied there, but by mistake. In Mesa 13 they included that file in `noinst_HEADERS` (ie, headers necessary for compiling mesa, but not for compiling external software that required mesa). The sanity check worked because previous to mesa 13 they didn't correct that mistake, the header was copied during installation, but it was simply a header lying there, it shouldn't be used externally. That's at least my understanding.

**Comment by boegel** [comment]
OK, in that case it makes sense to exclude it from the sanity check, indeed, thanks.

Let's follow-up in #4354 (where we should clarify the change a bit with a better title/descr).
