### ISSUE TITLE
LMOD_DEFAULT_MODULEPATH issue

### ISSUE THREAD

**Issue by shahzebsiddiqui** [hpcugent/easybuild-easyconfigs#4361]
I am having an issue when building intel and some other packages. This problem has been showing up several times, I don't know what this issue is.

I have attached the build log. I am using Lmod version

[hpcswadm@amrndhl1157 intel]$ module --version

Modules based on Lua: Version 6.5.1  2016-08-17 15:44
    by Robert McLay mclay@tacc.utexas.edu

[hpcswadm@amrndhl1157 intel]$ echo $LMOD_DEFAULT_MODULEPATH 
/usr/share/lmod/lmod/modulefiles/Core:/nfs/grid/software/RHEL7-BUILD/easybuild/modules/all:/nfs/grid/software/testing/RHEL7/non-easybuild/modules/all:/nfs/grid/software/testing/RHEL7/easybuild/modules/all/Core:/nfs/grid/software/testing/moduledomains:/etc/modulefiles:/usr/share/modulefiles:/usr/share/modulefiles/Linux:/usr/share/modulefiles/Core

[hpcswadm@amrndhl1157 intel]$ eb intel-2017.01.eb --recursive-module-unload --robot --debug-lmod --debug
== temporary log file in case of crash /tmp/eb-vfNyiF/easybuild-ZwLT0S.log
== resolving dependencies ...
== processing EasyBuild easyconfig /hpc/hpcswadm/easybuild/icc/icc-2017.1.132-GCC-5.4.0-2.27.eb
== building and installing Core/icc/.2017.1.132-GCC-5.4.0-2.27...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== postprocessing...
== sanity checking...
== FAILED: Installation ended unsuccessfully (build directory: /nfs/grid/software/RHEL7-BUILD/easybuild/build/icc/2017.1.132/dummy-dummy-GCC-5.4.0-2.27): build failed (first 300 chars): Sanity check failed: loading fake module failed: 'Changing environment as dictated by module failed: name \'false\' is not defined (stdout: os.environ["LMOD_DEFAULT_MODULEPATH"] = "/nfs/grid/software/testing/RHEL7/easybuild/modules/all/Core:/tmp/eb-vfNyiF/tmp1XdfTH/all/Core:/nfs/grid/software/testin
== Results of the build can be found in the log file(s) /tmp/eb-vfNyiF/easybuild-icc-2017.1.132-20170317.094258.pGwIz.log
ERROR: Build of /hpc/hpcswadm/easybuild/icc/icc-2017.1.132-GCC-5.4.0-2.27.eb failed (err: 'build failed (first 300 chars): Sanity check failed: loading fake module failed: \'Changing environment as dictated by module failed: name \\\'false\\\' is not defined (stdout: os.environ["LMOD_DEFAULT_MODULEPATH"] = "/nfs/grid/software/testing/RHEL7/easybuild/modules/all/Core:/tmp/eb-vfNyiF/tmp1XdfTH/all/Core:/nfs/grid/software/testin')

[easybuild-icc-2017.1.132-20170317.094258.pGwIz.txt](https://github.com/hpcugent/easybuild-easyconfigs/files/850730/easybuild-icc-2017.1.132-20170317.094258.pGwIz.txt)
[intel.issa.hpcswadm.amrndhl1157.pfizer.com_03.17.09.43.48.2017.txt](https://github.com/hpcugent/easybuild-easyconfigs/files/850729/intel.issa.hpcswadm.amrndhl1157.pfizer.com_03.17.09.43.48.2017.txt)
[intel.pset.hpcswadm.amrndhl1157.pfizer.com_03.17.09.43.48.2017.txt](https://github.com/hpcugent/easybuild-easyconfigs/files/850731/intel.pset.hpcswadm.amrndhl1157.pfizer.com_03.17.09.43.48.2017.txt)

**Comment by boegel** [comment]
@shahzebsiddiqui Unfortunately you need to dive into the (debug) log to figure out why the module can not be loaded.

I assume this was the same problem as what was discussed in https://lists.ugent.be/wws/arc/easybuild/2017-03/msg00110.html ?
