### ISSUE TITLE
No module found for toolchain, but module is available.

### ISSUE THREAD

**Issue by shawarden** [hpcugent/easybuild-easyconfigs#4370]
I'm trying to build a small cluster for our university Genomics program and while trying to install TopHat (among others) with
```
eb TopHat-2.1.1-foss-2016a -r
```
and by extension, `foss-2016a` I run into a rather peculiar error. When easybuild gets to `OpenBLAS-0.2.15-GCC-4.9.3-2.25-LAPACK-3.6.0` it replies with
```
No module found for toolchain: GCC/4.9.3-2.25
```
Surely as a dependency that should be installed automatically with the robot option... but when checking what modules are available
```
module av 2>&1 | grep GCC/
```
replies with
```
GCC/4.7.2
GCC/4.8.2
GCC/4.8.3
GCC/4.8.4
GCC/4.9.2
GCC/4.9.3-2.25
GCC/5.4.0-2.26
GCC/6.3.0-2.27 (D)
```
so it looks like easybuild has already installed that likely with some other package.

This issue did not occur when installing
```
OpenBLAS/0.2.13-GCC-4.8.4-LAPACK-3.5.0
OpenBLAS/0.2.18-GCC-5.4.0-2.26-LAPACK-3.6.1
```
as dependencies of other packages.

Additionally `bzip2-1.0.6-foss-2016b` replies with
```
No module found for toolchain: foss/2016b
```
but
```
module av 2>&1 |  grep foss/
```
replies with
```
foss/2016b
```

Loading those modules prior installing doesn't resolve it.

Are the multiple version conflicting? The version is specified though so...

**Comment by boegel** [comment]
@shawarden Hmm, this is quite weird...

Which EasyBuild version is this, how is it configured (i.e. output of `eb --show-config`), which modules tool & version are you using (output of `module --version`)?

Can you provide a full debug log for this? Collect it with `eb bzip2-1.0.6-foss-2016b.eb --debug -r --disable-cleanup-tmpdir`, and then grab the log file at the location printed in the first line of output.

**Comment by shawarden** [comment]
eb version
```
 samh > ~ > eb --show-config
# Current EasyBuild configuration
# (C: command line argument, D: default value, E: environment variable, F: configuration file)
#
buildpath      (D) = /test-home/samh/.local/easybuild/build
installpath    (D) = /test-home/samh/.local/easybuild
repositorypath (D) = /test-home/samh/.local/easybuild/ebfiles_repo
robot-paths    (D) = /test-home/samh/.local/easybuild/software/EasyBuild/3.1.1/lib/python2.7/site-packages/easybuild_easyconfigs-3.1.1-py2.7.egg/easybuild/easyconfigs
sourcepath     (D) = /test-home/samh/.local/easybuild/sources
```
Module version
```
 samh > ~ > module --version 
Modules based on Lua: Version 6.5.1  2016-08-17 15:44
    by Robert McLay mclay@tacc.utexas.edu
```
[easybuild-bzip2-1.0.6.zip](https://github.com/hpcugent/easybuild-easyconfigs/files/854352/easybuild-bzip2-1.0.6.zip)

**Comment by boegel** [comment]
@shawarden The log is truncated for some reason, but the included test report showed that the installation of `bzip2` 1.0.6 on top of `foss/2016b` worked just fine?

**Comment by shawarden** [comment]
Sorry I was on mobile at the time so didn't notice that it succeeded this time.

TopHat-2.1.1-foss-2016a works now as well. I'm not sure what's changed but it seems to be working for the all packages that were dying with that error.

Thanks!

**Comment by boegel** [comment]
@shawarden Huh, ok, strange...

Let's close this issue then?

If you can ever reproduce this, please collect the debug log and reopen this issue.

**Comment by shawarden** [comment]
Will do. Thanks again.
