### ISSUE TITLE
nettle - Issue with libraries path in sanity check step

### ISSUE THREAD

**Issue by vanzod** [hpcugent/easybuild-easyconfigs#4696]
In the `nettle` easyconfig the sanity check targets library files in `<prefix>/lib64`. The problem is that this is only true for REHL and Gentoo, since they store 64bit libraries in `/usr/lib64`. Instead, Debian and Ubuntu store them in `/usr/lib`. `configure` tries to identify the presence of either one or the other (see line 6791) and sets the installation directory name accordingly. Hence when building on a Debian system it fails because it looks in `<prefix>/lib64` instead of `<prefix>/lib`.

Since it may be an issue of any other software that uses configure (I have not found any other yet), how would you suggest to solve this?

**Comment by boegel** [comment]
@vanzod You can enhance the sanity check by specifying alternatives, through a tuple `(..., ...)`; if either of the paths in the tuple are found, the check passes.

So, rather than checking for `'lib64/libnettle.a'`, you can check for `('lib/libnettle.a', 'lib64/libnettle.a')`.

**Comment by vanzod** [comment]
Solved

**Comment by boegel** [comment]
@vanzod No PR to change that in the central easyconfigs?

**Comment by vanzod** [comment]
Forgot. Thanks for the reminder

**Comment by vanzod** [comment]
Forgot. Thanks for the reminder
I will update the other easyconfigs once this one gets merged.

**Comment by vanzod** [comment]
All files patched. Closing
