### ISSUE TITLE
"with-openib" is deprecated, OpenMPI 1.7.3

### ISSUE THREAD

**Issue by georgets** [hpcugent/easybuild-easyconfigs#712]
configure: WARNING: **************************************************
configure: WARNING: The use of --with-openib is deprecated.
configure: WARNING: You should use --with-verbs instead.
configure: WARNING: Proceeding with the assumption you meant
configure: WARNING: --with-verbs=yes
configure: WARNING: (sleeping to let you read this message)
configure: WARNING: **************************************************

**Comment by boegel** [comment]
fixed in #1511
